/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProtectedRouteRouteImport } from './routes/_protected/route'
import { Route as AuthLayoutRouteRouteImport } from './routes/_authLayout/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AttendanceScanRouteImport } from './routes/attendance/scan'
import { Route as ApiHealthRouteImport } from './routes/api/health'
import { Route as ProtectedReportsRouteRouteImport } from './routes/_protected/reports/route'
import { Route as ProtectedUserManagementIndexRouteImport } from './routes/_protected/user-management/index'
import { Route as ProtectedSuppliersIndexRouteImport } from './routes/_protected/suppliers/index'
import { Route as ProtectedReportsIndexRouteImport } from './routes/_protected/reports/index'
import { Route as ProtectedOrderBookerIndexRouteImport } from './routes/_protected/order-booker/index'
import { Route as ProtectedOperatorIndexRouteImport } from './routes/_protected/operator/index'
import { Route as ProtectedHrIndexRouteImport } from './routes/_protected/hr/index'
import { Route as ProtectedDashboardIndexRouteImport } from './routes/_protected/dashboard/index'
import { Route as AuthLayoutSignUpIndexRouteImport } from './routes/_authLayout/sign-up/index'
import { Route as AuthLayoutResetPasswordIndexRouteImport } from './routes/_authLayout/reset-password/index'
import { Route as AuthLayoutLoginIndexRouteImport } from './routes/_authLayout/login/index'
import { Route as AuthLayoutForgotPasswordIndexRouteImport } from './routes/_authLayout/forgot-password/index'
import { Route as AuthLayout2FaIndexRouteImport } from './routes/_authLayout/2-fa/index'
import { Route as ApiInternalBootstrapAdminRouteImport } from './routes/api/internal/bootstrap-admin'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ProtectedSuppliersSupplierIdRouteImport } from './routes/_protected/suppliers/$supplierId'
import { Route as ProtectedSalesOfflineRouteImport } from './routes/_protected/sales/offline'
import { Route as ProtectedOperatorRunIdRouteImport } from './routes/_protected/operator/$runId'
import { Route as ProtectedFinancePaymentVerificationRouteImport } from './routes/_protected/finance/payment-verification'
import { Route as ProtectedSalesRecoveryIndexRouteImport } from './routes/_protected/sales/recovery/index'
import { Route as ProtectedSalesReconciliationIndexRouteImport } from './routes/_protected/sales/reconciliation/index'
import { Route as ProtectedSalesPeopleIndexRouteImport } from './routes/_protected/sales/people/index'
import { Route as ProtectedSalesOverviewIndexRouteImport } from './routes/_protected/sales/overview/index'
import { Route as ProtectedSalesOrdersIndexRouteImport } from './routes/_protected/sales/orders/index'
import { Route as ProtectedSalesNewInvoiceIndexRouteImport } from './routes/_protected/sales/new-invoice/index'
import { Route as ProtectedSalesCustomersIndexRouteImport } from './routes/_protected/sales/customers/index'
import { Route as ProtectedSalesConfigurationsIndexRouteImport } from './routes/_protected/sales/configurations/index'
import { Route as ProtectedReportsSalesIndexRouteImport } from './routes/_protected/reports/sales/index'
import { Route as ProtectedReportsSalariesIndexRouteImport } from './routes/_protected/reports/salaries/index'
import { Route as ProtectedReportsPurchasesIndexRouteImport } from './routes/_protected/reports/purchases/index'
import { Route as ProtectedReportsProfitLossIndexRouteImport } from './routes/_protected/reports/profit-loss/index'
import { Route as ProtectedReportsOutstandingIndexRouteImport } from './routes/_protected/reports/outstanding/index'
import { Route as ProtectedReportsExpensesIndexRouteImport } from './routes/_protected/reports/expenses/index'
import { Route as ProtectedReportsCollectionsIndexRouteImport } from './routes/_protected/reports/collections/index'
import { Route as ProtectedOrderBookerTripsIndexRouteImport } from './routes/_protected/order-booker/trips/index'
import { Route as ProtectedOrderBookerRecoveriesIndexRouteImport } from './routes/_protected/order-booker/recoveries/index'
import { Route as ProtectedOrderBookerOrdersIndexRouteImport } from './routes/_protected/order-booker/orders/index'
import { Route as ProtectedOrderBookerCommissionIndexRouteImport } from './routes/_protected/order-booker/commission/index'
import { Route as ProtectedManufacturingRecipesIndexRouteImport } from './routes/_protected/manufacturing/recipes/index'
import { Route as ProtectedManufacturingProductionsIndexRouteImport } from './routes/_protected/manufacturing/productions/index'
import { Route as ProtectedInventoryWarehousesIndexRouteImport } from './routes/_protected/inventory/warehouses/index'
import { Route as ProtectedInventoryFactoryFloorIndexRouteImport } from './routes/_protected/inventory/factory-floor/index'
import { Route as ProtectedHrSettingsIndexRouteImport } from './routes/_protected/hr/settings/index'
import { Route as ProtectedHrPayrollIndexRouteImport } from './routes/_protected/hr/payroll/index'
import { Route as ProtectedHrEmployeesIndexRouteImport } from './routes/_protected/hr/employees/index'
import { Route as ProtectedHrAttendanceIndexRouteImport } from './routes/_protected/hr/attendance/index'
import { Route as ProtectedHrApprovalsIndexRouteImport } from './routes/_protected/hr/approvals/index'
import { Route as ProtectedFinanceLedgerIndexRouteImport } from './routes/_protected/finance/ledger/index'
import { Route as ProtectedFinanceExpensesIndexRouteImport } from './routes/_protected/finance/expenses/index'
import { Route as ProtectedFinanceAccountsIndexRouteImport } from './routes/_protected/finance/accounts/index'
import { Route as ProtectedDashboardActivityTimelineIndexRouteImport } from './routes/_protected/dashboard/activity-timeline/index'
import { Route as ProtectedSuppliersSupplierIdDetailsRouteImport } from './routes/_protected/suppliers/$supplierId_.details'
import { Route as ProtectedManufacturingRecipesRecipeIdRouteImport } from './routes/_protected/manufacturing/recipes/$recipeId'
import { Route as ProtectedHrOrderBookerDetailsEmployeeIdRouteImport } from './routes/_protected/hr/order-booker-details/$employeeId'
import { Route as ProtectedHrEmployeesEmployeeIdRouteImport } from './routes/_protected/hr/employees/$employeeId'
import { Route as ProtectedHrAttendanceOfflineRouteImport } from './routes/_protected/hr/attendance/offline'
import { Route as ProtectedHrAttendanceEmployeeIdRouteImport } from './routes/_protected/hr/attendance/$employeeId'
import { Route as ProtectedManufacturingProductionsRunIdRouteRouteImport } from './routes/_protected/manufacturing/productions/$runId/route'
import { Route as ProtectedSalesInvoicesInvoiceIdIndexRouteImport } from './routes/_protected/sales/invoices/$invoiceId/index'
import { Route as ProtectedSalesCustomersCustomerIdIndexRouteImport } from './routes/_protected/sales/customers/$customerId/index'
import { Route as ProtectedManufacturingProductsProductIdIndexRouteImport } from './routes/_protected/manufacturing/products/$productId/index'
import { Route as ProtectedManufacturingProductionsRunIdIndexRouteImport } from './routes/_protected/manufacturing/productions/$runId/index'
import { Route as ProtectedHrPayrollEmployeeIndexRouteImport } from './routes/_protected/hr/payroll/employee/index'
import { Route as ProtectedFinanceExpensesSettingsIndexRouteImport } from './routes/_protected/finance/expenses/settings/index'
import { Route as ProtectedInventoryFactoryFloorCartonsRecipeIdRouteImport } from './routes/_protected/inventory/factory-floor/cartons/$recipeId'
import { Route as ProtectedHrPayrollEmployeeEmployeeIdRouteImport } from './routes/_protected/hr/payroll/employee/$employeeId'
import { Route as ProtectedSalesPeopleShopkeepersCustomerIdIndexRouteImport } from './routes/_protected/sales/people/shopkeepers/$customerId/index'
import { Route as ProtectedSalesPeopleSalesmenSalesmanIdIndexRouteImport } from './routes/_protected/sales/people/salesmen/$salesmanId/index'
import { Route as ProtectedSalesPeopleOrderBookersOrderBookerIdIndexRouteImport } from './routes/_protected/sales/people/order-bookers/$orderBookerId/index'
import { Route as ProtectedSalesPeopleDistributorsCustomerIdIndexRouteImport } from './routes/_protected/sales/people/distributors/$customerId/index'
import { Route as ProtectedReportsProfitLossRecipeRecipeIdIndexRouteImport } from './routes/_protected/reports/profit-loss/recipe/$recipeId/index'
import { Route as ProtectedReportsProfitLossProductProductIdIndexRouteImport } from './routes/_protected/reports/profit-loss/product/$productId/index'
import { Route as ProtectedManufacturingProductionsRunIdCartonsIndexRouteImport } from './routes/_protected/manufacturing/productions/$runId/cartons/index'
import { Route as ProtectedInventoryItemItemTypeItemIdIndexRouteImport } from './routes/_protected/inventory/item/$itemType/$itemId/index'
import { Route as ProtectedSalesPeopleShopkeepersCustomerIdLedgerRouteImport } from './routes/_protected/sales/people/shopkeepers/$customerId/ledger'
import { Route as ProtectedSalesPeopleSalesmenSalesmanIdLedgerRouteImport } from './routes/_protected/sales/people/salesmen/$salesmanId/ledger'
import { Route as ProtectedSalesPeopleDistributorsCustomerIdLedgerRouteImport } from './routes/_protected/sales/people/distributors/$customerId/ledger'
import { Route as ProtectedSalesPeopleSalesmenSalesmanIdShopsCustomerIdRouteImport } from './routes/_protected/sales/people/salesmen/$salesmanId/shops/$customerId'

const ProtectedRouteRoute = ProtectedRouteRouteImport.update({
  id: '/_protected',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLayoutRouteRoute = AuthLayoutRouteRouteImport.update({
  id: '/_authLayout',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AttendanceScanRoute = AttendanceScanRouteImport.update({
  id: '/attendance/scan',
  path: '/attendance/scan',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedReportsRouteRoute = ProtectedReportsRouteRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => ProtectedRouteRoute,
} as any)
const ProtectedUserManagementIndexRoute =
  ProtectedUserManagementIndexRouteImport.update({
    id: '/user-management/',
    path: '/user-management/',
    getParentRoute: () => ProtectedRouteRoute,
  } as any)
const ProtectedSuppliersIndexRoute = ProtectedSuppliersIndexRouteImport.update({
  id: '/suppliers/',
  path: '/suppliers/',
  getParentRoute: () => ProtectedRouteRoute,
} as any)
const ProtectedReportsIndexRoute = ProtectedReportsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProtectedReportsRouteRoute,
} as any)
const ProtectedOrderBookerIndexRoute =
  ProtectedOrderBookerIndexRouteImport.update({
    id: '/order-booker/',
    path: '/order-booker/',
    getParentRoute: () => ProtectedRouteRoute,
  } as any)
const ProtectedOperatorIndexRoute = ProtectedOperatorIndexRouteImport.update({
  id: '/operator/',
  path: '/operator/',
  getParentRoute: () => ProtectedRouteRoute,
} as any)
const ProtectedHrIndexRoute = ProtectedHrIndexRouteImport.update({
  id: '/hr/',
  path: '/hr/',
  getParentRoute: () => ProtectedRouteRoute,
} as any)
const ProtectedDashboardIndexRoute = ProtectedDashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => ProtectedRouteRoute,
} as any)
const AuthLayoutSignUpIndexRoute = AuthLayoutSignUpIndexRouteImport.update({
  id: '/sign-up/',
  path: '/sign-up/',
  getParentRoute: () => AuthLayoutRouteRoute,
} as any)
const AuthLayoutResetPasswordIndexRoute =
  AuthLayoutResetPasswordIndexRouteImport.update({
    id: '/reset-password/',
    path: '/reset-password/',
    getParentRoute: () => AuthLayoutRouteRoute,
  } as any)
const AuthLayoutLoginIndexRoute = AuthLayoutLoginIndexRouteImport.update({
  id: '/login/',
  path: '/login/',
  getParentRoute: () => AuthLayoutRouteRoute,
} as any)
const AuthLayoutForgotPasswordIndexRoute =
  AuthLayoutForgotPasswordIndexRouteImport.update({
    id: '/forgot-password/',
    path: '/forgot-password/',
    getParentRoute: () => AuthLayoutRouteRoute,
  } as any)
const AuthLayout2FaIndexRoute = AuthLayout2FaIndexRouteImport.update({
  id: '/2-fa/',
  path: '/2-fa/',
  getParentRoute: () => AuthLayoutRouteRoute,
} as any)
const ApiInternalBootstrapAdminRoute =
  ApiInternalBootstrapAdminRouteImport.update({
    id: '/api/internal/bootstrap-admin',
    path: '/api/internal/bootstrap-admin',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedSuppliersSupplierIdRoute =
  ProtectedSuppliersSupplierIdRouteImport.update({
    id: '/suppliers/$supplierId',
    path: '/suppliers/$supplierId',
    getParentRoute: () => ProtectedRouteRoute,
  } as any)
const ProtectedSalesOfflineRoute = ProtectedSalesOfflineRouteImport.update({
  id: '/sales/offline',
  path: '/sales/offline',
  getParentRoute: () => ProtectedRouteRoute,
} as any)
const ProtectedOperatorRunIdRoute = ProtectedOperatorRunIdRouteImport.update({
  id: '/operator/$runId',
  path: '/operator/$runId',
  getParentRoute: () => ProtectedRouteRoute,
} as any)
const ProtectedFinancePaymentVerificationRoute =
  ProtectedFinancePaymentVerificationRouteImport.update({
    id: '/finance/payment-verification',
    path: '/finance/payment-verification',
    getParentRoute: () => ProtectedRouteRoute,
  } as any)
const ProtectedSalesRecoveryIndexRoute =
  ProtectedSalesRecoveryIndexRouteImport.update({
    id: '/sales/recovery/',
    path: '/sales/recovery/',
    getParentRoute: () => ProtectedRouteRoute,
  } as any)
const ProtectedSalesReconciliationIndexRoute =
  ProtectedSalesReconciliationIndexRouteImport.update({
    id: '/sales/reconciliation/',
    path: '/sales/reconciliation/',
    getParentRoute: () => ProtectedRouteRoute,
  } as any)
const ProtectedSalesPeopleIndexRoute =
  ProtectedSalesPeopleIndexRouteImport.update({
    id: '/sales/people/',
    path: '/sales/people/',
    getParentRoute: () => ProtectedRouteRoute,
  } as any)
const ProtectedSalesOverviewIndexRoute =
  ProtectedSalesOverviewIndexRouteImport.update({
    id: '/sales/overview/',
    path: '/sales/overview/',
    getParentRoute: () => ProtectedRouteRoute,
  } as any)
const ProtectedSalesOrdersIndexRoute =
  ProtectedSalesOrdersIndexRouteImport.update({
    id: '/sales/orders/',
    path: '/sales/orders/',
    getParentRoute: () => ProtectedRouteRoute,
  } as any)
const ProtectedSalesNewInvoiceIndexRoute =
  ProtectedSalesNewInvoiceIndexRouteImport.update({
    id: '/sales/new-invoice/',
    path: '/sales/new-invoice/',
    getParentRoute: () => ProtectedRouteRoute,
  } as any)
const ProtectedSalesCustomersIndexRoute =
  ProtectedSalesCustomersIndexRouteImport.update({
    id: '/sales/customers/',
    path: '/sales/customers/',
    getParentRoute: () => ProtectedRouteRoute,
  } as any)
const ProtectedSalesConfigurationsIndexRoute =
  ProtectedSalesConfigurationsIndexRouteImport.update({
    id: '/sales/configurations/',
    path: '/sales/configurations/',
    getParentRoute: () => ProtectedRouteRoute,
  } as any)
const ProtectedReportsSalesIndexRoute =
  ProtectedReportsSalesIndexRouteImport.update({
    id: '/sales/',
    path: '/sales/',
    getParentRoute: () => ProtectedReportsRouteRoute,
  } as any)
const ProtectedReportsSalariesIndexRoute =
  ProtectedReportsSalariesIndexRouteImport.update({
    id: '/salaries/',
    path: '/salaries/',
    getParentRoute: () => ProtectedReportsRouteRoute,
  } as any)
const ProtectedReportsPurchasesIndexRoute =
  ProtectedReportsPurchasesIndexRouteImport.update({
    id: '/purchases/',
    path: '/purchases/',
    getParentRoute: () => ProtectedReportsRouteRoute,
  } as any)
const ProtectedReportsProfitLossIndexRoute =
  ProtectedReportsProfitLossIndexRouteImport.update({
    id: '/profit-loss/',
    path: '/profit-loss/',
    getParentRoute: () => ProtectedReportsRouteRoute,
  } as any)
const ProtectedReportsOutstandingIndexRoute =
  ProtectedReportsOutstandingIndexRouteImport.update({
    id: '/outstanding/',
    path: '/outstanding/',
    getParentRoute: () => ProtectedReportsRouteRoute,
  } as any)
const ProtectedReportsExpensesIndexRoute =
  ProtectedReportsExpensesIndexRouteImport.update({
    id: '/expenses/',
    path: '/expenses/',
    getParentRoute: () => ProtectedReportsRouteRoute,
  } as any)
const ProtectedReportsCollectionsIndexRoute =
  ProtectedReportsCollectionsIndexRouteImport.update({
    id: '/collections/',
    path: '/collections/',
    getParentRoute: () => ProtectedReportsRouteRoute,
  } as any)
const ProtectedOrderBookerTripsIndexRoute =
  ProtectedOrderBookerTripsIndexRouteImport.update({
    id: '/order-booker/trips/',
    path: '/order-booker/trips/',
    getParentRoute: () => ProtectedRouteRoute,
  } as any)
const ProtectedOrderBookerRecoveriesIndexRoute =
  ProtectedOrderBookerRecoveriesIndexRouteImport.update({
    id: '/order-booker/recoveries/',
    path: '/order-booker/recoveries/',
    getParentRoute: () => ProtectedRouteRoute,
  } as any)
const ProtectedOrderBookerOrdersIndexRoute =
  ProtectedOrderBookerOrdersIndexRouteImport.update({
    id: '/order-booker/orders/',
    path: '/order-booker/orders/',
    getParentRoute: () => ProtectedRouteRoute,
  } as any)
const ProtectedOrderBookerCommissionIndexRoute =
  ProtectedOrderBookerCommissionIndexRouteImport.update({
    id: '/order-booker/commission/',
    path: '/order-booker/commission/',
    getParentRoute: () => ProtectedRouteRoute,
  } as any)
const ProtectedManufacturingRecipesIndexRoute =
  ProtectedManufacturingRecipesIndexRouteImport.update({
    id: '/manufacturing/recipes/',
    path: '/manufacturing/recipes/',
    getParentRoute: () => ProtectedRouteRoute,
  } as any)
const ProtectedManufacturingProductionsIndexRoute =
  ProtectedManufacturingProductionsIndexRouteImport.update({
    id: '/manufacturing/productions/',
    path: '/manufacturing/productions/',
    getParentRoute: () => ProtectedRouteRoute,
  } as any)
const ProtectedInventoryWarehousesIndexRoute =
  ProtectedInventoryWarehousesIndexRouteImport.update({
    id: '/inventory/warehouses/',
    path: '/inventory/warehouses/',
    getParentRoute: () => ProtectedRouteRoute,
  } as any)
const ProtectedInventoryFactoryFloorIndexRoute =
  ProtectedInventoryFactoryFloorIndexRouteImport.update({
    id: '/inventory/factory-floor/',
    path: '/inventory/factory-floor/',
    getParentRoute: () => ProtectedRouteRoute,
  } as any)
const ProtectedHrSettingsIndexRoute =
  ProtectedHrSettingsIndexRouteImport.update({
    id: '/hr/settings/',
    path: '/hr/settings/',
    getParentRoute: () => ProtectedRouteRoute,
  } as any)
const ProtectedHrPayrollIndexRoute = ProtectedHrPayrollIndexRouteImport.update({
  id: '/hr/payroll/',
  path: '/hr/payroll/',
  getParentRoute: () => ProtectedRouteRoute,
} as any)
const ProtectedHrEmployeesIndexRoute =
  ProtectedHrEmployeesIndexRouteImport.update({
    id: '/hr/employees/',
    path: '/hr/employees/',
    getParentRoute: () => ProtectedRouteRoute,
  } as any)
const ProtectedHrAttendanceIndexRoute =
  ProtectedHrAttendanceIndexRouteImport.update({
    id: '/hr/attendance/',
    path: '/hr/attendance/',
    getParentRoute: () => ProtectedRouteRoute,
  } as any)
const ProtectedHrApprovalsIndexRoute =
  ProtectedHrApprovalsIndexRouteImport.update({
    id: '/hr/approvals/',
    path: '/hr/approvals/',
    getParentRoute: () => ProtectedRouteRoute,
  } as any)
const ProtectedFinanceLedgerIndexRoute =
  ProtectedFinanceLedgerIndexRouteImport.update({
    id: '/finance/ledger/',
    path: '/finance/ledger/',
    getParentRoute: () => ProtectedRouteRoute,
  } as any)
const ProtectedFinanceExpensesIndexRoute =
  ProtectedFinanceExpensesIndexRouteImport.update({
    id: '/finance/expenses/',
    path: '/finance/expenses/',
    getParentRoute: () => ProtectedRouteRoute,
  } as any)
const ProtectedFinanceAccountsIndexRoute =
  ProtectedFinanceAccountsIndexRouteImport.update({
    id: '/finance/accounts/',
    path: '/finance/accounts/',
    getParentRoute: () => ProtectedRouteRoute,
  } as any)
const ProtectedDashboardActivityTimelineIndexRoute =
  ProtectedDashboardActivityTimelineIndexRouteImport.update({
    id: '/dashboard/activity-timeline/',
    path: '/dashboard/activity-timeline/',
    getParentRoute: () => ProtectedRouteRoute,
  } as any)
const ProtectedSuppliersSupplierIdDetailsRoute =
  ProtectedSuppliersSupplierIdDetailsRouteImport.update({
    id: '/suppliers/$supplierId_/details',
    path: '/suppliers/$supplierId/details',
    getParentRoute: () => ProtectedRouteRoute,
  } as any)
const ProtectedManufacturingRecipesRecipeIdRoute =
  ProtectedManufacturingRecipesRecipeIdRouteImport.update({
    id: '/manufacturing/recipes/$recipeId',
    path: '/manufacturing/recipes/$recipeId',
    getParentRoute: () => ProtectedRouteRoute,
  } as any)
const ProtectedHrOrderBookerDetailsEmployeeIdRoute =
  ProtectedHrOrderBookerDetailsEmployeeIdRouteImport.update({
    id: '/hr/order-booker-details/$employeeId',
    path: '/hr/order-booker-details/$employeeId',
    getParentRoute: () => ProtectedRouteRoute,
  } as any)
const ProtectedHrEmployeesEmployeeIdRoute =
  ProtectedHrEmployeesEmployeeIdRouteImport.update({
    id: '/hr/employees/$employeeId',
    path: '/hr/employees/$employeeId',
    getParentRoute: () => ProtectedRouteRoute,
  } as any)
const ProtectedHrAttendanceOfflineRoute =
  ProtectedHrAttendanceOfflineRouteImport.update({
    id: '/hr/attendance/offline',
    path: '/hr/attendance/offline',
    getParentRoute: () => ProtectedRouteRoute,
  } as any)
const ProtectedHrAttendanceEmployeeIdRoute =
  ProtectedHrAttendanceEmployeeIdRouteImport.update({
    id: '/hr/attendance/$employeeId',
    path: '/hr/attendance/$employeeId',
    getParentRoute: () => ProtectedRouteRoute,
  } as any)
const ProtectedManufacturingProductionsRunIdRouteRoute =
  ProtectedManufacturingProductionsRunIdRouteRouteImport.update({
    id: '/manufacturing/productions/$runId',
    path: '/manufacturing/productions/$runId',
    getParentRoute: () => ProtectedRouteRoute,
  } as any)
const ProtectedSalesInvoicesInvoiceIdIndexRoute =
  ProtectedSalesInvoicesInvoiceIdIndexRouteImport.update({
    id: '/sales/invoices/$invoiceId/',
    path: '/sales/invoices/$invoiceId/',
    getParentRoute: () => ProtectedRouteRoute,
  } as any)
const ProtectedSalesCustomersCustomerIdIndexRoute =
  ProtectedSalesCustomersCustomerIdIndexRouteImport.update({
    id: '/sales/customers/$customerId/',
    path: '/sales/customers/$customerId/',
    getParentRoute: () => ProtectedRouteRoute,
  } as any)
const ProtectedManufacturingProductsProductIdIndexRoute =
  ProtectedManufacturingProductsProductIdIndexRouteImport.update({
    id: '/manufacturing/products/$productId/',
    path: '/manufacturing/products/$productId/',
    getParentRoute: () => ProtectedRouteRoute,
  } as any)
const ProtectedManufacturingProductionsRunIdIndexRoute =
  ProtectedManufacturingProductionsRunIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => ProtectedManufacturingProductionsRunIdRouteRoute,
  } as any)
const ProtectedHrPayrollEmployeeIndexRoute =
  ProtectedHrPayrollEmployeeIndexRouteImport.update({
    id: '/hr/payroll/employee/',
    path: '/hr/payroll/employee/',
    getParentRoute: () => ProtectedRouteRoute,
  } as any)
const ProtectedFinanceExpensesSettingsIndexRoute =
  ProtectedFinanceExpensesSettingsIndexRouteImport.update({
    id: '/finance/expenses/settings/',
    path: '/finance/expenses/settings/',
    getParentRoute: () => ProtectedRouteRoute,
  } as any)
const ProtectedInventoryFactoryFloorCartonsRecipeIdRoute =
  ProtectedInventoryFactoryFloorCartonsRecipeIdRouteImport.update({
    id: '/inventory/factory-floor/cartons/$recipeId',
    path: '/inventory/factory-floor/cartons/$recipeId',
    getParentRoute: () => ProtectedRouteRoute,
  } as any)
const ProtectedHrPayrollEmployeeEmployeeIdRoute =
  ProtectedHrPayrollEmployeeEmployeeIdRouteImport.update({
    id: '/hr/payroll/employee/$employeeId',
    path: '/hr/payroll/employee/$employeeId',
    getParentRoute: () => ProtectedRouteRoute,
  } as any)
const ProtectedSalesPeopleShopkeepersCustomerIdIndexRoute =
  ProtectedSalesPeopleShopkeepersCustomerIdIndexRouteImport.update({
    id: '/sales/people/shopkeepers/$customerId/',
    path: '/sales/people/shopkeepers/$customerId/',
    getParentRoute: () => ProtectedRouteRoute,
  } as any)
const ProtectedSalesPeopleSalesmenSalesmanIdIndexRoute =
  ProtectedSalesPeopleSalesmenSalesmanIdIndexRouteImport.update({
    id: '/sales/people/salesmen/$salesmanId/',
    path: '/sales/people/salesmen/$salesmanId/',
    getParentRoute: () => ProtectedRouteRoute,
  } as any)
const ProtectedSalesPeopleOrderBookersOrderBookerIdIndexRoute =
  ProtectedSalesPeopleOrderBookersOrderBookerIdIndexRouteImport.update({
    id: '/sales/people/order-bookers/$orderBookerId/',
    path: '/sales/people/order-bookers/$orderBookerId/',
    getParentRoute: () => ProtectedRouteRoute,
  } as any)
const ProtectedSalesPeopleDistributorsCustomerIdIndexRoute =
  ProtectedSalesPeopleDistributorsCustomerIdIndexRouteImport.update({
    id: '/sales/people/distributors/$customerId/',
    path: '/sales/people/distributors/$customerId/',
    getParentRoute: () => ProtectedRouteRoute,
  } as any)
const ProtectedReportsProfitLossRecipeRecipeIdIndexRoute =
  ProtectedReportsProfitLossRecipeRecipeIdIndexRouteImport.update({
    id: '/profit-loss/recipe/$recipeId/',
    path: '/profit-loss/recipe/$recipeId/',
    getParentRoute: () => ProtectedReportsRouteRoute,
  } as any)
const ProtectedReportsProfitLossProductProductIdIndexRoute =
  ProtectedReportsProfitLossProductProductIdIndexRouteImport.update({
    id: '/profit-loss/product/$productId/',
    path: '/profit-loss/product/$productId/',
    getParentRoute: () => ProtectedReportsRouteRoute,
  } as any)
const ProtectedManufacturingProductionsRunIdCartonsIndexRoute =
  ProtectedManufacturingProductionsRunIdCartonsIndexRouteImport.update({
    id: '/cartons/',
    path: '/cartons/',
    getParentRoute: () => ProtectedManufacturingProductionsRunIdRouteRoute,
  } as any)
const ProtectedInventoryItemItemTypeItemIdIndexRoute =
  ProtectedInventoryItemItemTypeItemIdIndexRouteImport.update({
    id: '/inventory/item/$itemType/$itemId/',
    path: '/inventory/item/$itemType/$itemId/',
    getParentRoute: () => ProtectedRouteRoute,
  } as any)
const ProtectedSalesPeopleShopkeepersCustomerIdLedgerRoute =
  ProtectedSalesPeopleShopkeepersCustomerIdLedgerRouteImport.update({
    id: '/sales/people/shopkeepers/$customerId/ledger',
    path: '/sales/people/shopkeepers/$customerId/ledger',
    getParentRoute: () => ProtectedRouteRoute,
  } as any)
const ProtectedSalesPeopleSalesmenSalesmanIdLedgerRoute =
  ProtectedSalesPeopleSalesmenSalesmanIdLedgerRouteImport.update({
    id: '/sales/people/salesmen/$salesmanId/ledger',
    path: '/sales/people/salesmen/$salesmanId/ledger',
    getParentRoute: () => ProtectedRouteRoute,
  } as any)
const ProtectedSalesPeopleDistributorsCustomerIdLedgerRoute =
  ProtectedSalesPeopleDistributorsCustomerIdLedgerRouteImport.update({
    id: '/sales/people/distributors/$customerId/ledger',
    path: '/sales/people/distributors/$customerId/ledger',
    getParentRoute: () => ProtectedRouteRoute,
  } as any)
const ProtectedSalesPeopleSalesmenSalesmanIdShopsCustomerIdRoute =
  ProtectedSalesPeopleSalesmenSalesmanIdShopsCustomerIdRouteImport.update({
    id: '/sales/people/salesmen/$salesmanId/shops/$customerId',
    path: '/sales/people/salesmen/$salesmanId/shops/$customerId',
    getParentRoute: () => ProtectedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/reports': typeof ProtectedReportsRouteRouteWithChildren
  '/api/health': typeof ApiHealthRoute
  '/attendance/scan': typeof AttendanceScanRoute
  '/finance/payment-verification': typeof ProtectedFinancePaymentVerificationRoute
  '/operator/$runId': typeof ProtectedOperatorRunIdRoute
  '/sales/offline': typeof ProtectedSalesOfflineRoute
  '/suppliers/$supplierId': typeof ProtectedSuppliersSupplierIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/internal/bootstrap-admin': typeof ApiInternalBootstrapAdminRoute
  '/2-fa/': typeof AuthLayout2FaIndexRoute
  '/forgot-password/': typeof AuthLayoutForgotPasswordIndexRoute
  '/login/': typeof AuthLayoutLoginIndexRoute
  '/reset-password/': typeof AuthLayoutResetPasswordIndexRoute
  '/sign-up/': typeof AuthLayoutSignUpIndexRoute
  '/dashboard/': typeof ProtectedDashboardIndexRoute
  '/hr/': typeof ProtectedHrIndexRoute
  '/operator/': typeof ProtectedOperatorIndexRoute
  '/order-booker/': typeof ProtectedOrderBookerIndexRoute
  '/reports/': typeof ProtectedReportsIndexRoute
  '/suppliers/': typeof ProtectedSuppliersIndexRoute
  '/user-management/': typeof ProtectedUserManagementIndexRoute
  '/manufacturing/productions/$runId': typeof ProtectedManufacturingProductionsRunIdRouteRouteWithChildren
  '/hr/attendance/$employeeId': typeof ProtectedHrAttendanceEmployeeIdRoute
  '/hr/attendance/offline': typeof ProtectedHrAttendanceOfflineRoute
  '/hr/employees/$employeeId': typeof ProtectedHrEmployeesEmployeeIdRoute
  '/hr/order-booker-details/$employeeId': typeof ProtectedHrOrderBookerDetailsEmployeeIdRoute
  '/manufacturing/recipes/$recipeId': typeof ProtectedManufacturingRecipesRecipeIdRoute
  '/suppliers/$supplierId/details': typeof ProtectedSuppliersSupplierIdDetailsRoute
  '/dashboard/activity-timeline/': typeof ProtectedDashboardActivityTimelineIndexRoute
  '/finance/accounts/': typeof ProtectedFinanceAccountsIndexRoute
  '/finance/expenses/': typeof ProtectedFinanceExpensesIndexRoute
  '/finance/ledger/': typeof ProtectedFinanceLedgerIndexRoute
  '/hr/approvals/': typeof ProtectedHrApprovalsIndexRoute
  '/hr/attendance/': typeof ProtectedHrAttendanceIndexRoute
  '/hr/employees/': typeof ProtectedHrEmployeesIndexRoute
  '/hr/payroll/': typeof ProtectedHrPayrollIndexRoute
  '/hr/settings/': typeof ProtectedHrSettingsIndexRoute
  '/inventory/factory-floor/': typeof ProtectedInventoryFactoryFloorIndexRoute
  '/inventory/warehouses/': typeof ProtectedInventoryWarehousesIndexRoute
  '/manufacturing/productions/': typeof ProtectedManufacturingProductionsIndexRoute
  '/manufacturing/recipes/': typeof ProtectedManufacturingRecipesIndexRoute
  '/order-booker/commission/': typeof ProtectedOrderBookerCommissionIndexRoute
  '/order-booker/orders/': typeof ProtectedOrderBookerOrdersIndexRoute
  '/order-booker/recoveries/': typeof ProtectedOrderBookerRecoveriesIndexRoute
  '/order-booker/trips/': typeof ProtectedOrderBookerTripsIndexRoute
  '/reports/collections/': typeof ProtectedReportsCollectionsIndexRoute
  '/reports/expenses/': typeof ProtectedReportsExpensesIndexRoute
  '/reports/outstanding/': typeof ProtectedReportsOutstandingIndexRoute
  '/reports/profit-loss/': typeof ProtectedReportsProfitLossIndexRoute
  '/reports/purchases/': typeof ProtectedReportsPurchasesIndexRoute
  '/reports/salaries/': typeof ProtectedReportsSalariesIndexRoute
  '/reports/sales/': typeof ProtectedReportsSalesIndexRoute
  '/sales/configurations/': typeof ProtectedSalesConfigurationsIndexRoute
  '/sales/customers/': typeof ProtectedSalesCustomersIndexRoute
  '/sales/new-invoice/': typeof ProtectedSalesNewInvoiceIndexRoute
  '/sales/orders/': typeof ProtectedSalesOrdersIndexRoute
  '/sales/overview/': typeof ProtectedSalesOverviewIndexRoute
  '/sales/people/': typeof ProtectedSalesPeopleIndexRoute
  '/sales/reconciliation/': typeof ProtectedSalesReconciliationIndexRoute
  '/sales/recovery/': typeof ProtectedSalesRecoveryIndexRoute
  '/hr/payroll/employee/$employeeId': typeof ProtectedHrPayrollEmployeeEmployeeIdRoute
  '/inventory/factory-floor/cartons/$recipeId': typeof ProtectedInventoryFactoryFloorCartonsRecipeIdRoute
  '/finance/expenses/settings/': typeof ProtectedFinanceExpensesSettingsIndexRoute
  '/hr/payroll/employee/': typeof ProtectedHrPayrollEmployeeIndexRoute
  '/manufacturing/productions/$runId/': typeof ProtectedManufacturingProductionsRunIdIndexRoute
  '/manufacturing/products/$productId/': typeof ProtectedManufacturingProductsProductIdIndexRoute
  '/sales/customers/$customerId/': typeof ProtectedSalesCustomersCustomerIdIndexRoute
  '/sales/invoices/$invoiceId/': typeof ProtectedSalesInvoicesInvoiceIdIndexRoute
  '/sales/people/distributors/$customerId/ledger': typeof ProtectedSalesPeopleDistributorsCustomerIdLedgerRoute
  '/sales/people/salesmen/$salesmanId/ledger': typeof ProtectedSalesPeopleSalesmenSalesmanIdLedgerRoute
  '/sales/people/shopkeepers/$customerId/ledger': typeof ProtectedSalesPeopleShopkeepersCustomerIdLedgerRoute
  '/inventory/item/$itemType/$itemId/': typeof ProtectedInventoryItemItemTypeItemIdIndexRoute
  '/manufacturing/productions/$runId/cartons/': typeof ProtectedManufacturingProductionsRunIdCartonsIndexRoute
  '/reports/profit-loss/product/$productId/': typeof ProtectedReportsProfitLossProductProductIdIndexRoute
  '/reports/profit-loss/recipe/$recipeId/': typeof ProtectedReportsProfitLossRecipeRecipeIdIndexRoute
  '/sales/people/distributors/$customerId/': typeof ProtectedSalesPeopleDistributorsCustomerIdIndexRoute
  '/sales/people/order-bookers/$orderBookerId/': typeof ProtectedSalesPeopleOrderBookersOrderBookerIdIndexRoute
  '/sales/people/salesmen/$salesmanId/': typeof ProtectedSalesPeopleSalesmenSalesmanIdIndexRoute
  '/sales/people/shopkeepers/$customerId/': typeof ProtectedSalesPeopleShopkeepersCustomerIdIndexRoute
  '/sales/people/salesmen/$salesmanId/shops/$customerId': typeof ProtectedSalesPeopleSalesmenSalesmanIdShopsCustomerIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/health': typeof ApiHealthRoute
  '/attendance/scan': typeof AttendanceScanRoute
  '/finance/payment-verification': typeof ProtectedFinancePaymentVerificationRoute
  '/operator/$runId': typeof ProtectedOperatorRunIdRoute
  '/sales/offline': typeof ProtectedSalesOfflineRoute
  '/suppliers/$supplierId': typeof ProtectedSuppliersSupplierIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/internal/bootstrap-admin': typeof ApiInternalBootstrapAdminRoute
  '/2-fa': typeof AuthLayout2FaIndexRoute
  '/forgot-password': typeof AuthLayoutForgotPasswordIndexRoute
  '/login': typeof AuthLayoutLoginIndexRoute
  '/reset-password': typeof AuthLayoutResetPasswordIndexRoute
  '/sign-up': typeof AuthLayoutSignUpIndexRoute
  '/dashboard': typeof ProtectedDashboardIndexRoute
  '/hr': typeof ProtectedHrIndexRoute
  '/operator': typeof ProtectedOperatorIndexRoute
  '/order-booker': typeof ProtectedOrderBookerIndexRoute
  '/reports': typeof ProtectedReportsIndexRoute
  '/suppliers': typeof ProtectedSuppliersIndexRoute
  '/user-management': typeof ProtectedUserManagementIndexRoute
  '/hr/attendance/$employeeId': typeof ProtectedHrAttendanceEmployeeIdRoute
  '/hr/attendance/offline': typeof ProtectedHrAttendanceOfflineRoute
  '/hr/employees/$employeeId': typeof ProtectedHrEmployeesEmployeeIdRoute
  '/hr/order-booker-details/$employeeId': typeof ProtectedHrOrderBookerDetailsEmployeeIdRoute
  '/manufacturing/recipes/$recipeId': typeof ProtectedManufacturingRecipesRecipeIdRoute
  '/suppliers/$supplierId/details': typeof ProtectedSuppliersSupplierIdDetailsRoute
  '/dashboard/activity-timeline': typeof ProtectedDashboardActivityTimelineIndexRoute
  '/finance/accounts': typeof ProtectedFinanceAccountsIndexRoute
  '/finance/expenses': typeof ProtectedFinanceExpensesIndexRoute
  '/finance/ledger': typeof ProtectedFinanceLedgerIndexRoute
  '/hr/approvals': typeof ProtectedHrApprovalsIndexRoute
  '/hr/attendance': typeof ProtectedHrAttendanceIndexRoute
  '/hr/employees': typeof ProtectedHrEmployeesIndexRoute
  '/hr/payroll': typeof ProtectedHrPayrollIndexRoute
  '/hr/settings': typeof ProtectedHrSettingsIndexRoute
  '/inventory/factory-floor': typeof ProtectedInventoryFactoryFloorIndexRoute
  '/inventory/warehouses': typeof ProtectedInventoryWarehousesIndexRoute
  '/manufacturing/productions': typeof ProtectedManufacturingProductionsIndexRoute
  '/manufacturing/recipes': typeof ProtectedManufacturingRecipesIndexRoute
  '/order-booker/commission': typeof ProtectedOrderBookerCommissionIndexRoute
  '/order-booker/orders': typeof ProtectedOrderBookerOrdersIndexRoute
  '/order-booker/recoveries': typeof ProtectedOrderBookerRecoveriesIndexRoute
  '/order-booker/trips': typeof ProtectedOrderBookerTripsIndexRoute
  '/reports/collections': typeof ProtectedReportsCollectionsIndexRoute
  '/reports/expenses': typeof ProtectedReportsExpensesIndexRoute
  '/reports/outstanding': typeof ProtectedReportsOutstandingIndexRoute
  '/reports/profit-loss': typeof ProtectedReportsProfitLossIndexRoute
  '/reports/purchases': typeof ProtectedReportsPurchasesIndexRoute
  '/reports/salaries': typeof ProtectedReportsSalariesIndexRoute
  '/reports/sales': typeof ProtectedReportsSalesIndexRoute
  '/sales/configurations': typeof ProtectedSalesConfigurationsIndexRoute
  '/sales/customers': typeof ProtectedSalesCustomersIndexRoute
  '/sales/new-invoice': typeof ProtectedSalesNewInvoiceIndexRoute
  '/sales/orders': typeof ProtectedSalesOrdersIndexRoute
  '/sales/overview': typeof ProtectedSalesOverviewIndexRoute
  '/sales/people': typeof ProtectedSalesPeopleIndexRoute
  '/sales/reconciliation': typeof ProtectedSalesReconciliationIndexRoute
  '/sales/recovery': typeof ProtectedSalesRecoveryIndexRoute
  '/hr/payroll/employee/$employeeId': typeof ProtectedHrPayrollEmployeeEmployeeIdRoute
  '/inventory/factory-floor/cartons/$recipeId': typeof ProtectedInventoryFactoryFloorCartonsRecipeIdRoute
  '/finance/expenses/settings': typeof ProtectedFinanceExpensesSettingsIndexRoute
  '/hr/payroll/employee': typeof ProtectedHrPayrollEmployeeIndexRoute
  '/manufacturing/productions/$runId': typeof ProtectedManufacturingProductionsRunIdIndexRoute
  '/manufacturing/products/$productId': typeof ProtectedManufacturingProductsProductIdIndexRoute
  '/sales/customers/$customerId': typeof ProtectedSalesCustomersCustomerIdIndexRoute
  '/sales/invoices/$invoiceId': typeof ProtectedSalesInvoicesInvoiceIdIndexRoute
  '/sales/people/distributors/$customerId/ledger': typeof ProtectedSalesPeopleDistributorsCustomerIdLedgerRoute
  '/sales/people/salesmen/$salesmanId/ledger': typeof ProtectedSalesPeopleSalesmenSalesmanIdLedgerRoute
  '/sales/people/shopkeepers/$customerId/ledger': typeof ProtectedSalesPeopleShopkeepersCustomerIdLedgerRoute
  '/inventory/item/$itemType/$itemId': typeof ProtectedInventoryItemItemTypeItemIdIndexRoute
  '/manufacturing/productions/$runId/cartons': typeof ProtectedManufacturingProductionsRunIdCartonsIndexRoute
  '/reports/profit-loss/product/$productId': typeof ProtectedReportsProfitLossProductProductIdIndexRoute
  '/reports/profit-loss/recipe/$recipeId': typeof ProtectedReportsProfitLossRecipeRecipeIdIndexRoute
  '/sales/people/distributors/$customerId': typeof ProtectedSalesPeopleDistributorsCustomerIdIndexRoute
  '/sales/people/order-bookers/$orderBookerId': typeof ProtectedSalesPeopleOrderBookersOrderBookerIdIndexRoute
  '/sales/people/salesmen/$salesmanId': typeof ProtectedSalesPeopleSalesmenSalesmanIdIndexRoute
  '/sales/people/shopkeepers/$customerId': typeof ProtectedSalesPeopleShopkeepersCustomerIdIndexRoute
  '/sales/people/salesmen/$salesmanId/shops/$customerId': typeof ProtectedSalesPeopleSalesmenSalesmanIdShopsCustomerIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authLayout': typeof AuthLayoutRouteRouteWithChildren
  '/_protected': typeof ProtectedRouteRouteWithChildren
  '/_protected/reports': typeof ProtectedReportsRouteRouteWithChildren
  '/api/health': typeof ApiHealthRoute
  '/attendance/scan': typeof AttendanceScanRoute
  '/_protected/finance/payment-verification': typeof ProtectedFinancePaymentVerificationRoute
  '/_protected/operator/$runId': typeof ProtectedOperatorRunIdRoute
  '/_protected/sales/offline': typeof ProtectedSalesOfflineRoute
  '/_protected/suppliers/$supplierId': typeof ProtectedSuppliersSupplierIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/internal/bootstrap-admin': typeof ApiInternalBootstrapAdminRoute
  '/_authLayout/2-fa/': typeof AuthLayout2FaIndexRoute
  '/_authLayout/forgot-password/': typeof AuthLayoutForgotPasswordIndexRoute
  '/_authLayout/login/': typeof AuthLayoutLoginIndexRoute
  '/_authLayout/reset-password/': typeof AuthLayoutResetPasswordIndexRoute
  '/_authLayout/sign-up/': typeof AuthLayoutSignUpIndexRoute
  '/_protected/dashboard/': typeof ProtectedDashboardIndexRoute
  '/_protected/hr/': typeof ProtectedHrIndexRoute
  '/_protected/operator/': typeof ProtectedOperatorIndexRoute
  '/_protected/order-booker/': typeof ProtectedOrderBookerIndexRoute
  '/_protected/reports/': typeof ProtectedReportsIndexRoute
  '/_protected/suppliers/': typeof ProtectedSuppliersIndexRoute
  '/_protected/user-management/': typeof ProtectedUserManagementIndexRoute
  '/_protected/manufacturing/productions/$runId': typeof ProtectedManufacturingProductionsRunIdRouteRouteWithChildren
  '/_protected/hr/attendance/$employeeId': typeof ProtectedHrAttendanceEmployeeIdRoute
  '/_protected/hr/attendance/offline': typeof ProtectedHrAttendanceOfflineRoute
  '/_protected/hr/employees/$employeeId': typeof ProtectedHrEmployeesEmployeeIdRoute
  '/_protected/hr/order-booker-details/$employeeId': typeof ProtectedHrOrderBookerDetailsEmployeeIdRoute
  '/_protected/manufacturing/recipes/$recipeId': typeof ProtectedManufacturingRecipesRecipeIdRoute
  '/_protected/suppliers/$supplierId_/details': typeof ProtectedSuppliersSupplierIdDetailsRoute
  '/_protected/dashboard/activity-timeline/': typeof ProtectedDashboardActivityTimelineIndexRoute
  '/_protected/finance/accounts/': typeof ProtectedFinanceAccountsIndexRoute
  '/_protected/finance/expenses/': typeof ProtectedFinanceExpensesIndexRoute
  '/_protected/finance/ledger/': typeof ProtectedFinanceLedgerIndexRoute
  '/_protected/hr/approvals/': typeof ProtectedHrApprovalsIndexRoute
  '/_protected/hr/attendance/': typeof ProtectedHrAttendanceIndexRoute
  '/_protected/hr/employees/': typeof ProtectedHrEmployeesIndexRoute
  '/_protected/hr/payroll/': typeof ProtectedHrPayrollIndexRoute
  '/_protected/hr/settings/': typeof ProtectedHrSettingsIndexRoute
  '/_protected/inventory/factory-floor/': typeof ProtectedInventoryFactoryFloorIndexRoute
  '/_protected/inventory/warehouses/': typeof ProtectedInventoryWarehousesIndexRoute
  '/_protected/manufacturing/productions/': typeof ProtectedManufacturingProductionsIndexRoute
  '/_protected/manufacturing/recipes/': typeof ProtectedManufacturingRecipesIndexRoute
  '/_protected/order-booker/commission/': typeof ProtectedOrderBookerCommissionIndexRoute
  '/_protected/order-booker/orders/': typeof ProtectedOrderBookerOrdersIndexRoute
  '/_protected/order-booker/recoveries/': typeof ProtectedOrderBookerRecoveriesIndexRoute
  '/_protected/order-booker/trips/': typeof ProtectedOrderBookerTripsIndexRoute
  '/_protected/reports/collections/': typeof ProtectedReportsCollectionsIndexRoute
  '/_protected/reports/expenses/': typeof ProtectedReportsExpensesIndexRoute
  '/_protected/reports/outstanding/': typeof ProtectedReportsOutstandingIndexRoute
  '/_protected/reports/profit-loss/': typeof ProtectedReportsProfitLossIndexRoute
  '/_protected/reports/purchases/': typeof ProtectedReportsPurchasesIndexRoute
  '/_protected/reports/salaries/': typeof ProtectedReportsSalariesIndexRoute
  '/_protected/reports/sales/': typeof ProtectedReportsSalesIndexRoute
  '/_protected/sales/configurations/': typeof ProtectedSalesConfigurationsIndexRoute
  '/_protected/sales/customers/': typeof ProtectedSalesCustomersIndexRoute
  '/_protected/sales/new-invoice/': typeof ProtectedSalesNewInvoiceIndexRoute
  '/_protected/sales/orders/': typeof ProtectedSalesOrdersIndexRoute
  '/_protected/sales/overview/': typeof ProtectedSalesOverviewIndexRoute
  '/_protected/sales/people/': typeof ProtectedSalesPeopleIndexRoute
  '/_protected/sales/reconciliation/': typeof ProtectedSalesReconciliationIndexRoute
  '/_protected/sales/recovery/': typeof ProtectedSalesRecoveryIndexRoute
  '/_protected/hr/payroll/employee/$employeeId': typeof ProtectedHrPayrollEmployeeEmployeeIdRoute
  '/_protected/inventory/factory-floor/cartons/$recipeId': typeof ProtectedInventoryFactoryFloorCartonsRecipeIdRoute
  '/_protected/finance/expenses/settings/': typeof ProtectedFinanceExpensesSettingsIndexRoute
  '/_protected/hr/payroll/employee/': typeof ProtectedHrPayrollEmployeeIndexRoute
  '/_protected/manufacturing/productions/$runId/': typeof ProtectedManufacturingProductionsRunIdIndexRoute
  '/_protected/manufacturing/products/$productId/': typeof ProtectedManufacturingProductsProductIdIndexRoute
  '/_protected/sales/customers/$customerId/': typeof ProtectedSalesCustomersCustomerIdIndexRoute
  '/_protected/sales/invoices/$invoiceId/': typeof ProtectedSalesInvoicesInvoiceIdIndexRoute
  '/_protected/sales/people/distributors/$customerId/ledger': typeof ProtectedSalesPeopleDistributorsCustomerIdLedgerRoute
  '/_protected/sales/people/salesmen/$salesmanId/ledger': typeof ProtectedSalesPeopleSalesmenSalesmanIdLedgerRoute
  '/_protected/sales/people/shopkeepers/$customerId/ledger': typeof ProtectedSalesPeopleShopkeepersCustomerIdLedgerRoute
  '/_protected/inventory/item/$itemType/$itemId/': typeof ProtectedInventoryItemItemTypeItemIdIndexRoute
  '/_protected/manufacturing/productions/$runId/cartons/': typeof ProtectedManufacturingProductionsRunIdCartonsIndexRoute
  '/_protected/reports/profit-loss/product/$productId/': typeof ProtectedReportsProfitLossProductProductIdIndexRoute
  '/_protected/reports/profit-loss/recipe/$recipeId/': typeof ProtectedReportsProfitLossRecipeRecipeIdIndexRoute
  '/_protected/sales/people/distributors/$customerId/': typeof ProtectedSalesPeopleDistributorsCustomerIdIndexRoute
  '/_protected/sales/people/order-bookers/$orderBookerId/': typeof ProtectedSalesPeopleOrderBookersOrderBookerIdIndexRoute
  '/_protected/sales/people/salesmen/$salesmanId/': typeof ProtectedSalesPeopleSalesmenSalesmanIdIndexRoute
  '/_protected/sales/people/shopkeepers/$customerId/': typeof ProtectedSalesPeopleShopkeepersCustomerIdIndexRoute
  '/_protected/sales/people/salesmen/$salesmanId/shops/$customerId': typeof ProtectedSalesPeopleSalesmenSalesmanIdShopsCustomerIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/reports'
    | '/api/health'
    | '/attendance/scan'
    | '/finance/payment-verification'
    | '/operator/$runId'
    | '/sales/offline'
    | '/suppliers/$supplierId'
    | '/api/auth/$'
    | '/api/internal/bootstrap-admin'
    | '/2-fa/'
    | '/forgot-password/'
    | '/login/'
    | '/reset-password/'
    | '/sign-up/'
    | '/dashboard/'
    | '/hr/'
    | '/operator/'
    | '/order-booker/'
    | '/reports/'
    | '/suppliers/'
    | '/user-management/'
    | '/manufacturing/productions/$runId'
    | '/hr/attendance/$employeeId'
    | '/hr/attendance/offline'
    | '/hr/employees/$employeeId'
    | '/hr/order-booker-details/$employeeId'
    | '/manufacturing/recipes/$recipeId'
    | '/suppliers/$supplierId/details'
    | '/dashboard/activity-timeline/'
    | '/finance/accounts/'
    | '/finance/expenses/'
    | '/finance/ledger/'
    | '/hr/approvals/'
    | '/hr/attendance/'
    | '/hr/employees/'
    | '/hr/payroll/'
    | '/hr/settings/'
    | '/inventory/factory-floor/'
    | '/inventory/warehouses/'
    | '/manufacturing/productions/'
    | '/manufacturing/recipes/'
    | '/order-booker/commission/'
    | '/order-booker/orders/'
    | '/order-booker/recoveries/'
    | '/order-booker/trips/'
    | '/reports/collections/'
    | '/reports/expenses/'
    | '/reports/outstanding/'
    | '/reports/profit-loss/'
    | '/reports/purchases/'
    | '/reports/salaries/'
    | '/reports/sales/'
    | '/sales/configurations/'
    | '/sales/customers/'
    | '/sales/new-invoice/'
    | '/sales/orders/'
    | '/sales/overview/'
    | '/sales/people/'
    | '/sales/reconciliation/'
    | '/sales/recovery/'
    | '/hr/payroll/employee/$employeeId'
    | '/inventory/factory-floor/cartons/$recipeId'
    | '/finance/expenses/settings/'
    | '/hr/payroll/employee/'
    | '/manufacturing/productions/$runId/'
    | '/manufacturing/products/$productId/'
    | '/sales/customers/$customerId/'
    | '/sales/invoices/$invoiceId/'
    | '/sales/people/distributors/$customerId/ledger'
    | '/sales/people/salesmen/$salesmanId/ledger'
    | '/sales/people/shopkeepers/$customerId/ledger'
    | '/inventory/item/$itemType/$itemId/'
    | '/manufacturing/productions/$runId/cartons/'
    | '/reports/profit-loss/product/$productId/'
    | '/reports/profit-loss/recipe/$recipeId/'
    | '/sales/people/distributors/$customerId/'
    | '/sales/people/order-bookers/$orderBookerId/'
    | '/sales/people/salesmen/$salesmanId/'
    | '/sales/people/shopkeepers/$customerId/'
    | '/sales/people/salesmen/$salesmanId/shops/$customerId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api/health'
    | '/attendance/scan'
    | '/finance/payment-verification'
    | '/operator/$runId'
    | '/sales/offline'
    | '/suppliers/$supplierId'
    | '/api/auth/$'
    | '/api/internal/bootstrap-admin'
    | '/2-fa'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/sign-up'
    | '/dashboard'
    | '/hr'
    | '/operator'
    | '/order-booker'
    | '/reports'
    | '/suppliers'
    | '/user-management'
    | '/hr/attendance/$employeeId'
    | '/hr/attendance/offline'
    | '/hr/employees/$employeeId'
    | '/hr/order-booker-details/$employeeId'
    | '/manufacturing/recipes/$recipeId'
    | '/suppliers/$supplierId/details'
    | '/dashboard/activity-timeline'
    | '/finance/accounts'
    | '/finance/expenses'
    | '/finance/ledger'
    | '/hr/approvals'
    | '/hr/attendance'
    | '/hr/employees'
    | '/hr/payroll'
    | '/hr/settings'
    | '/inventory/factory-floor'
    | '/inventory/warehouses'
    | '/manufacturing/productions'
    | '/manufacturing/recipes'
    | '/order-booker/commission'
    | '/order-booker/orders'
    | '/order-booker/recoveries'
    | '/order-booker/trips'
    | '/reports/collections'
    | '/reports/expenses'
    | '/reports/outstanding'
    | '/reports/profit-loss'
    | '/reports/purchases'
    | '/reports/salaries'
    | '/reports/sales'
    | '/sales/configurations'
    | '/sales/customers'
    | '/sales/new-invoice'
    | '/sales/orders'
    | '/sales/overview'
    | '/sales/people'
    | '/sales/reconciliation'
    | '/sales/recovery'
    | '/hr/payroll/employee/$employeeId'
    | '/inventory/factory-floor/cartons/$recipeId'
    | '/finance/expenses/settings'
    | '/hr/payroll/employee'
    | '/manufacturing/productions/$runId'
    | '/manufacturing/products/$productId'
    | '/sales/customers/$customerId'
    | '/sales/invoices/$invoiceId'
    | '/sales/people/distributors/$customerId/ledger'
    | '/sales/people/salesmen/$salesmanId/ledger'
    | '/sales/people/shopkeepers/$customerId/ledger'
    | '/inventory/item/$itemType/$itemId'
    | '/manufacturing/productions/$runId/cartons'
    | '/reports/profit-loss/product/$productId'
    | '/reports/profit-loss/recipe/$recipeId'
    | '/sales/people/distributors/$customerId'
    | '/sales/people/order-bookers/$orderBookerId'
    | '/sales/people/salesmen/$salesmanId'
    | '/sales/people/shopkeepers/$customerId'
    | '/sales/people/salesmen/$salesmanId/shops/$customerId'
  id:
    | '__root__'
    | '/'
    | '/_authLayout'
    | '/_protected'
    | '/_protected/reports'
    | '/api/health'
    | '/attendance/scan'
    | '/_protected/finance/payment-verification'
    | '/_protected/operator/$runId'
    | '/_protected/sales/offline'
    | '/_protected/suppliers/$supplierId'
    | '/api/auth/$'
    | '/api/internal/bootstrap-admin'
    | '/_authLayout/2-fa/'
    | '/_authLayout/forgot-password/'
    | '/_authLayout/login/'
    | '/_authLayout/reset-password/'
    | '/_authLayout/sign-up/'
    | '/_protected/dashboard/'
    | '/_protected/hr/'
    | '/_protected/operator/'
    | '/_protected/order-booker/'
    | '/_protected/reports/'
    | '/_protected/suppliers/'
    | '/_protected/user-management/'
    | '/_protected/manufacturing/productions/$runId'
    | '/_protected/hr/attendance/$employeeId'
    | '/_protected/hr/attendance/offline'
    | '/_protected/hr/employees/$employeeId'
    | '/_protected/hr/order-booker-details/$employeeId'
    | '/_protected/manufacturing/recipes/$recipeId'
    | '/_protected/suppliers/$supplierId_/details'
    | '/_protected/dashboard/activity-timeline/'
    | '/_protected/finance/accounts/'
    | '/_protected/finance/expenses/'
    | '/_protected/finance/ledger/'
    | '/_protected/hr/approvals/'
    | '/_protected/hr/attendance/'
    | '/_protected/hr/employees/'
    | '/_protected/hr/payroll/'
    | '/_protected/hr/settings/'
    | '/_protected/inventory/factory-floor/'
    | '/_protected/inventory/warehouses/'
    | '/_protected/manufacturing/productions/'
    | '/_protected/manufacturing/recipes/'
    | '/_protected/order-booker/commission/'
    | '/_protected/order-booker/orders/'
    | '/_protected/order-booker/recoveries/'
    | '/_protected/order-booker/trips/'
    | '/_protected/reports/collections/'
    | '/_protected/reports/expenses/'
    | '/_protected/reports/outstanding/'
    | '/_protected/reports/profit-loss/'
    | '/_protected/reports/purchases/'
    | '/_protected/reports/salaries/'
    | '/_protected/reports/sales/'
    | '/_protected/sales/configurations/'
    | '/_protected/sales/customers/'
    | '/_protected/sales/new-invoice/'
    | '/_protected/sales/orders/'
    | '/_protected/sales/overview/'
    | '/_protected/sales/people/'
    | '/_protected/sales/reconciliation/'
    | '/_protected/sales/recovery/'
    | '/_protected/hr/payroll/employee/$employeeId'
    | '/_protected/inventory/factory-floor/cartons/$recipeId'
    | '/_protected/finance/expenses/settings/'
    | '/_protected/hr/payroll/employee/'
    | '/_protected/manufacturing/productions/$runId/'
    | '/_protected/manufacturing/products/$productId/'
    | '/_protected/sales/customers/$customerId/'
    | '/_protected/sales/invoices/$invoiceId/'
    | '/_protected/sales/people/distributors/$customerId/ledger'
    | '/_protected/sales/people/salesmen/$salesmanId/ledger'
    | '/_protected/sales/people/shopkeepers/$customerId/ledger'
    | '/_protected/inventory/item/$itemType/$itemId/'
    | '/_protected/manufacturing/productions/$runId/cartons/'
    | '/_protected/reports/profit-loss/product/$productId/'
    | '/_protected/reports/profit-loss/recipe/$recipeId/'
    | '/_protected/sales/people/distributors/$customerId/'
    | '/_protected/sales/people/order-bookers/$orderBookerId/'
    | '/_protected/sales/people/salesmen/$salesmanId/'
    | '/_protected/sales/people/shopkeepers/$customerId/'
    | '/_protected/sales/people/salesmen/$salesmanId/shops/$customerId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthLayoutRouteRoute: typeof AuthLayoutRouteRouteWithChildren
  ProtectedRouteRoute: typeof ProtectedRouteRouteWithChildren
  ApiHealthRoute: typeof ApiHealthRoute
  AttendanceScanRoute: typeof AttendanceScanRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiInternalBootstrapAdminRoute: typeof ApiInternalBootstrapAdminRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_protected': {
      id: '/_protected'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ProtectedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authLayout': {
      id: '/_authLayout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthLayoutRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/attendance/scan': {
      id: '/attendance/scan'
      path: '/attendance/scan'
      fullPath: '/attendance/scan'
      preLoaderRoute: typeof AttendanceScanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/reports': {
      id: '/_protected/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ProtectedReportsRouteRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/user-management/': {
      id: '/_protected/user-management/'
      path: '/user-management'
      fullPath: '/user-management/'
      preLoaderRoute: typeof ProtectedUserManagementIndexRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/suppliers/': {
      id: '/_protected/suppliers/'
      path: '/suppliers'
      fullPath: '/suppliers/'
      preLoaderRoute: typeof ProtectedSuppliersIndexRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/reports/': {
      id: '/_protected/reports/'
      path: '/'
      fullPath: '/reports/'
      preLoaderRoute: typeof ProtectedReportsIndexRouteImport
      parentRoute: typeof ProtectedReportsRouteRoute
    }
    '/_protected/order-booker/': {
      id: '/_protected/order-booker/'
      path: '/order-booker'
      fullPath: '/order-booker/'
      preLoaderRoute: typeof ProtectedOrderBookerIndexRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/operator/': {
      id: '/_protected/operator/'
      path: '/operator'
      fullPath: '/operator/'
      preLoaderRoute: typeof ProtectedOperatorIndexRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/hr/': {
      id: '/_protected/hr/'
      path: '/hr'
      fullPath: '/hr/'
      preLoaderRoute: typeof ProtectedHrIndexRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/dashboard/': {
      id: '/_protected/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof ProtectedDashboardIndexRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_authLayout/sign-up/': {
      id: '/_authLayout/sign-up/'
      path: '/sign-up'
      fullPath: '/sign-up/'
      preLoaderRoute: typeof AuthLayoutSignUpIndexRouteImport
      parentRoute: typeof AuthLayoutRouteRoute
    }
    '/_authLayout/reset-password/': {
      id: '/_authLayout/reset-password/'
      path: '/reset-password'
      fullPath: '/reset-password/'
      preLoaderRoute: typeof AuthLayoutResetPasswordIndexRouteImport
      parentRoute: typeof AuthLayoutRouteRoute
    }
    '/_authLayout/login/': {
      id: '/_authLayout/login/'
      path: '/login'
      fullPath: '/login/'
      preLoaderRoute: typeof AuthLayoutLoginIndexRouteImport
      parentRoute: typeof AuthLayoutRouteRoute
    }
    '/_authLayout/forgot-password/': {
      id: '/_authLayout/forgot-password/'
      path: '/forgot-password'
      fullPath: '/forgot-password/'
      preLoaderRoute: typeof AuthLayoutForgotPasswordIndexRouteImport
      parentRoute: typeof AuthLayoutRouteRoute
    }
    '/_authLayout/2-fa/': {
      id: '/_authLayout/2-fa/'
      path: '/2-fa'
      fullPath: '/2-fa/'
      preLoaderRoute: typeof AuthLayout2FaIndexRouteImport
      parentRoute: typeof AuthLayoutRouteRoute
    }
    '/api/internal/bootstrap-admin': {
      id: '/api/internal/bootstrap-admin'
      path: '/api/internal/bootstrap-admin'
      fullPath: '/api/internal/bootstrap-admin'
      preLoaderRoute: typeof ApiInternalBootstrapAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/suppliers/$supplierId': {
      id: '/_protected/suppliers/$supplierId'
      path: '/suppliers/$supplierId'
      fullPath: '/suppliers/$supplierId'
      preLoaderRoute: typeof ProtectedSuppliersSupplierIdRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/sales/offline': {
      id: '/_protected/sales/offline'
      path: '/sales/offline'
      fullPath: '/sales/offline'
      preLoaderRoute: typeof ProtectedSalesOfflineRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/operator/$runId': {
      id: '/_protected/operator/$runId'
      path: '/operator/$runId'
      fullPath: '/operator/$runId'
      preLoaderRoute: typeof ProtectedOperatorRunIdRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/finance/payment-verification': {
      id: '/_protected/finance/payment-verification'
      path: '/finance/payment-verification'
      fullPath: '/finance/payment-verification'
      preLoaderRoute: typeof ProtectedFinancePaymentVerificationRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/sales/recovery/': {
      id: '/_protected/sales/recovery/'
      path: '/sales/recovery'
      fullPath: '/sales/recovery/'
      preLoaderRoute: typeof ProtectedSalesRecoveryIndexRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/sales/reconciliation/': {
      id: '/_protected/sales/reconciliation/'
      path: '/sales/reconciliation'
      fullPath: '/sales/reconciliation/'
      preLoaderRoute: typeof ProtectedSalesReconciliationIndexRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/sales/people/': {
      id: '/_protected/sales/people/'
      path: '/sales/people'
      fullPath: '/sales/people/'
      preLoaderRoute: typeof ProtectedSalesPeopleIndexRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/sales/overview/': {
      id: '/_protected/sales/overview/'
      path: '/sales/overview'
      fullPath: '/sales/overview/'
      preLoaderRoute: typeof ProtectedSalesOverviewIndexRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/sales/orders/': {
      id: '/_protected/sales/orders/'
      path: '/sales/orders'
      fullPath: '/sales/orders/'
      preLoaderRoute: typeof ProtectedSalesOrdersIndexRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/sales/new-invoice/': {
      id: '/_protected/sales/new-invoice/'
      path: '/sales/new-invoice'
      fullPath: '/sales/new-invoice/'
      preLoaderRoute: typeof ProtectedSalesNewInvoiceIndexRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/sales/customers/': {
      id: '/_protected/sales/customers/'
      path: '/sales/customers'
      fullPath: '/sales/customers/'
      preLoaderRoute: typeof ProtectedSalesCustomersIndexRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/sales/configurations/': {
      id: '/_protected/sales/configurations/'
      path: '/sales/configurations'
      fullPath: '/sales/configurations/'
      preLoaderRoute: typeof ProtectedSalesConfigurationsIndexRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/reports/sales/': {
      id: '/_protected/reports/sales/'
      path: '/sales'
      fullPath: '/reports/sales/'
      preLoaderRoute: typeof ProtectedReportsSalesIndexRouteImport
      parentRoute: typeof ProtectedReportsRouteRoute
    }
    '/_protected/reports/salaries/': {
      id: '/_protected/reports/salaries/'
      path: '/salaries'
      fullPath: '/reports/salaries/'
      preLoaderRoute: typeof ProtectedReportsSalariesIndexRouteImport
      parentRoute: typeof ProtectedReportsRouteRoute
    }
    '/_protected/reports/purchases/': {
      id: '/_protected/reports/purchases/'
      path: '/purchases'
      fullPath: '/reports/purchases/'
      preLoaderRoute: typeof ProtectedReportsPurchasesIndexRouteImport
      parentRoute: typeof ProtectedReportsRouteRoute
    }
    '/_protected/reports/profit-loss/': {
      id: '/_protected/reports/profit-loss/'
      path: '/profit-loss'
      fullPath: '/reports/profit-loss/'
      preLoaderRoute: typeof ProtectedReportsProfitLossIndexRouteImport
      parentRoute: typeof ProtectedReportsRouteRoute
    }
    '/_protected/reports/outstanding/': {
      id: '/_protected/reports/outstanding/'
      path: '/outstanding'
      fullPath: '/reports/outstanding/'
      preLoaderRoute: typeof ProtectedReportsOutstandingIndexRouteImport
      parentRoute: typeof ProtectedReportsRouteRoute
    }
    '/_protected/reports/expenses/': {
      id: '/_protected/reports/expenses/'
      path: '/expenses'
      fullPath: '/reports/expenses/'
      preLoaderRoute: typeof ProtectedReportsExpensesIndexRouteImport
      parentRoute: typeof ProtectedReportsRouteRoute
    }
    '/_protected/reports/collections/': {
      id: '/_protected/reports/collections/'
      path: '/collections'
      fullPath: '/reports/collections/'
      preLoaderRoute: typeof ProtectedReportsCollectionsIndexRouteImport
      parentRoute: typeof ProtectedReportsRouteRoute
    }
    '/_protected/order-booker/trips/': {
      id: '/_protected/order-booker/trips/'
      path: '/order-booker/trips'
      fullPath: '/order-booker/trips/'
      preLoaderRoute: typeof ProtectedOrderBookerTripsIndexRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/order-booker/recoveries/': {
      id: '/_protected/order-booker/recoveries/'
      path: '/order-booker/recoveries'
      fullPath: '/order-booker/recoveries/'
      preLoaderRoute: typeof ProtectedOrderBookerRecoveriesIndexRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/order-booker/orders/': {
      id: '/_protected/order-booker/orders/'
      path: '/order-booker/orders'
      fullPath: '/order-booker/orders/'
      preLoaderRoute: typeof ProtectedOrderBookerOrdersIndexRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/order-booker/commission/': {
      id: '/_protected/order-booker/commission/'
      path: '/order-booker/commission'
      fullPath: '/order-booker/commission/'
      preLoaderRoute: typeof ProtectedOrderBookerCommissionIndexRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/manufacturing/recipes/': {
      id: '/_protected/manufacturing/recipes/'
      path: '/manufacturing/recipes'
      fullPath: '/manufacturing/recipes/'
      preLoaderRoute: typeof ProtectedManufacturingRecipesIndexRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/manufacturing/productions/': {
      id: '/_protected/manufacturing/productions/'
      path: '/manufacturing/productions'
      fullPath: '/manufacturing/productions/'
      preLoaderRoute: typeof ProtectedManufacturingProductionsIndexRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/inventory/warehouses/': {
      id: '/_protected/inventory/warehouses/'
      path: '/inventory/warehouses'
      fullPath: '/inventory/warehouses/'
      preLoaderRoute: typeof ProtectedInventoryWarehousesIndexRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/inventory/factory-floor/': {
      id: '/_protected/inventory/factory-floor/'
      path: '/inventory/factory-floor'
      fullPath: '/inventory/factory-floor/'
      preLoaderRoute: typeof ProtectedInventoryFactoryFloorIndexRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/hr/settings/': {
      id: '/_protected/hr/settings/'
      path: '/hr/settings'
      fullPath: '/hr/settings/'
      preLoaderRoute: typeof ProtectedHrSettingsIndexRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/hr/payroll/': {
      id: '/_protected/hr/payroll/'
      path: '/hr/payroll'
      fullPath: '/hr/payroll/'
      preLoaderRoute: typeof ProtectedHrPayrollIndexRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/hr/employees/': {
      id: '/_protected/hr/employees/'
      path: '/hr/employees'
      fullPath: '/hr/employees/'
      preLoaderRoute: typeof ProtectedHrEmployeesIndexRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/hr/attendance/': {
      id: '/_protected/hr/attendance/'
      path: '/hr/attendance'
      fullPath: '/hr/attendance/'
      preLoaderRoute: typeof ProtectedHrAttendanceIndexRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/hr/approvals/': {
      id: '/_protected/hr/approvals/'
      path: '/hr/approvals'
      fullPath: '/hr/approvals/'
      preLoaderRoute: typeof ProtectedHrApprovalsIndexRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/finance/ledger/': {
      id: '/_protected/finance/ledger/'
      path: '/finance/ledger'
      fullPath: '/finance/ledger/'
      preLoaderRoute: typeof ProtectedFinanceLedgerIndexRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/finance/expenses/': {
      id: '/_protected/finance/expenses/'
      path: '/finance/expenses'
      fullPath: '/finance/expenses/'
      preLoaderRoute: typeof ProtectedFinanceExpensesIndexRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/finance/accounts/': {
      id: '/_protected/finance/accounts/'
      path: '/finance/accounts'
      fullPath: '/finance/accounts/'
      preLoaderRoute: typeof ProtectedFinanceAccountsIndexRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/dashboard/activity-timeline/': {
      id: '/_protected/dashboard/activity-timeline/'
      path: '/dashboard/activity-timeline'
      fullPath: '/dashboard/activity-timeline/'
      preLoaderRoute: typeof ProtectedDashboardActivityTimelineIndexRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/suppliers/$supplierId_/details': {
      id: '/_protected/suppliers/$supplierId_/details'
      path: '/suppliers/$supplierId/details'
      fullPath: '/suppliers/$supplierId/details'
      preLoaderRoute: typeof ProtectedSuppliersSupplierIdDetailsRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/manufacturing/recipes/$recipeId': {
      id: '/_protected/manufacturing/recipes/$recipeId'
      path: '/manufacturing/recipes/$recipeId'
      fullPath: '/manufacturing/recipes/$recipeId'
      preLoaderRoute: typeof ProtectedManufacturingRecipesRecipeIdRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/hr/order-booker-details/$employeeId': {
      id: '/_protected/hr/order-booker-details/$employeeId'
      path: '/hr/order-booker-details/$employeeId'
      fullPath: '/hr/order-booker-details/$employeeId'
      preLoaderRoute: typeof ProtectedHrOrderBookerDetailsEmployeeIdRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/hr/employees/$employeeId': {
      id: '/_protected/hr/employees/$employeeId'
      path: '/hr/employees/$employeeId'
      fullPath: '/hr/employees/$employeeId'
      preLoaderRoute: typeof ProtectedHrEmployeesEmployeeIdRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/hr/attendance/offline': {
      id: '/_protected/hr/attendance/offline'
      path: '/hr/attendance/offline'
      fullPath: '/hr/attendance/offline'
      preLoaderRoute: typeof ProtectedHrAttendanceOfflineRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/hr/attendance/$employeeId': {
      id: '/_protected/hr/attendance/$employeeId'
      path: '/hr/attendance/$employeeId'
      fullPath: '/hr/attendance/$employeeId'
      preLoaderRoute: typeof ProtectedHrAttendanceEmployeeIdRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/manufacturing/productions/$runId': {
      id: '/_protected/manufacturing/productions/$runId'
      path: '/manufacturing/productions/$runId'
      fullPath: '/manufacturing/productions/$runId'
      preLoaderRoute: typeof ProtectedManufacturingProductionsRunIdRouteRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/sales/invoices/$invoiceId/': {
      id: '/_protected/sales/invoices/$invoiceId/'
      path: '/sales/invoices/$invoiceId'
      fullPath: '/sales/invoices/$invoiceId/'
      preLoaderRoute: typeof ProtectedSalesInvoicesInvoiceIdIndexRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/sales/customers/$customerId/': {
      id: '/_protected/sales/customers/$customerId/'
      path: '/sales/customers/$customerId'
      fullPath: '/sales/customers/$customerId/'
      preLoaderRoute: typeof ProtectedSalesCustomersCustomerIdIndexRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/manufacturing/products/$productId/': {
      id: '/_protected/manufacturing/products/$productId/'
      path: '/manufacturing/products/$productId'
      fullPath: '/manufacturing/products/$productId/'
      preLoaderRoute: typeof ProtectedManufacturingProductsProductIdIndexRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/manufacturing/productions/$runId/': {
      id: '/_protected/manufacturing/productions/$runId/'
      path: '/'
      fullPath: '/manufacturing/productions/$runId/'
      preLoaderRoute: typeof ProtectedManufacturingProductionsRunIdIndexRouteImport
      parentRoute: typeof ProtectedManufacturingProductionsRunIdRouteRoute
    }
    '/_protected/hr/payroll/employee/': {
      id: '/_protected/hr/payroll/employee/'
      path: '/hr/payroll/employee'
      fullPath: '/hr/payroll/employee/'
      preLoaderRoute: typeof ProtectedHrPayrollEmployeeIndexRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/finance/expenses/settings/': {
      id: '/_protected/finance/expenses/settings/'
      path: '/finance/expenses/settings'
      fullPath: '/finance/expenses/settings/'
      preLoaderRoute: typeof ProtectedFinanceExpensesSettingsIndexRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/inventory/factory-floor/cartons/$recipeId': {
      id: '/_protected/inventory/factory-floor/cartons/$recipeId'
      path: '/inventory/factory-floor/cartons/$recipeId'
      fullPath: '/inventory/factory-floor/cartons/$recipeId'
      preLoaderRoute: typeof ProtectedInventoryFactoryFloorCartonsRecipeIdRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/hr/payroll/employee/$employeeId': {
      id: '/_protected/hr/payroll/employee/$employeeId'
      path: '/hr/payroll/employee/$employeeId'
      fullPath: '/hr/payroll/employee/$employeeId'
      preLoaderRoute: typeof ProtectedHrPayrollEmployeeEmployeeIdRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/sales/people/shopkeepers/$customerId/': {
      id: '/_protected/sales/people/shopkeepers/$customerId/'
      path: '/sales/people/shopkeepers/$customerId'
      fullPath: '/sales/people/shopkeepers/$customerId/'
      preLoaderRoute: typeof ProtectedSalesPeopleShopkeepersCustomerIdIndexRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/sales/people/salesmen/$salesmanId/': {
      id: '/_protected/sales/people/salesmen/$salesmanId/'
      path: '/sales/people/salesmen/$salesmanId'
      fullPath: '/sales/people/salesmen/$salesmanId/'
      preLoaderRoute: typeof ProtectedSalesPeopleSalesmenSalesmanIdIndexRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/sales/people/order-bookers/$orderBookerId/': {
      id: '/_protected/sales/people/order-bookers/$orderBookerId/'
      path: '/sales/people/order-bookers/$orderBookerId'
      fullPath: '/sales/people/order-bookers/$orderBookerId/'
      preLoaderRoute: typeof ProtectedSalesPeopleOrderBookersOrderBookerIdIndexRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/sales/people/distributors/$customerId/': {
      id: '/_protected/sales/people/distributors/$customerId/'
      path: '/sales/people/distributors/$customerId'
      fullPath: '/sales/people/distributors/$customerId/'
      preLoaderRoute: typeof ProtectedSalesPeopleDistributorsCustomerIdIndexRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/reports/profit-loss/recipe/$recipeId/': {
      id: '/_protected/reports/profit-loss/recipe/$recipeId/'
      path: '/profit-loss/recipe/$recipeId'
      fullPath: '/reports/profit-loss/recipe/$recipeId/'
      preLoaderRoute: typeof ProtectedReportsProfitLossRecipeRecipeIdIndexRouteImport
      parentRoute: typeof ProtectedReportsRouteRoute
    }
    '/_protected/reports/profit-loss/product/$productId/': {
      id: '/_protected/reports/profit-loss/product/$productId/'
      path: '/profit-loss/product/$productId'
      fullPath: '/reports/profit-loss/product/$productId/'
      preLoaderRoute: typeof ProtectedReportsProfitLossProductProductIdIndexRouteImport
      parentRoute: typeof ProtectedReportsRouteRoute
    }
    '/_protected/manufacturing/productions/$runId/cartons/': {
      id: '/_protected/manufacturing/productions/$runId/cartons/'
      path: '/cartons'
      fullPath: '/manufacturing/productions/$runId/cartons/'
      preLoaderRoute: typeof ProtectedManufacturingProductionsRunIdCartonsIndexRouteImport
      parentRoute: typeof ProtectedManufacturingProductionsRunIdRouteRoute
    }
    '/_protected/inventory/item/$itemType/$itemId/': {
      id: '/_protected/inventory/item/$itemType/$itemId/'
      path: '/inventory/item/$itemType/$itemId'
      fullPath: '/inventory/item/$itemType/$itemId/'
      preLoaderRoute: typeof ProtectedInventoryItemItemTypeItemIdIndexRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/sales/people/shopkeepers/$customerId/ledger': {
      id: '/_protected/sales/people/shopkeepers/$customerId/ledger'
      path: '/sales/people/shopkeepers/$customerId/ledger'
      fullPath: '/sales/people/shopkeepers/$customerId/ledger'
      preLoaderRoute: typeof ProtectedSalesPeopleShopkeepersCustomerIdLedgerRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/sales/people/salesmen/$salesmanId/ledger': {
      id: '/_protected/sales/people/salesmen/$salesmanId/ledger'
      path: '/sales/people/salesmen/$salesmanId/ledger'
      fullPath: '/sales/people/salesmen/$salesmanId/ledger'
      preLoaderRoute: typeof ProtectedSalesPeopleSalesmenSalesmanIdLedgerRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/sales/people/distributors/$customerId/ledger': {
      id: '/_protected/sales/people/distributors/$customerId/ledger'
      path: '/sales/people/distributors/$customerId/ledger'
      fullPath: '/sales/people/distributors/$customerId/ledger'
      preLoaderRoute: typeof ProtectedSalesPeopleDistributorsCustomerIdLedgerRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/sales/people/salesmen/$salesmanId/shops/$customerId': {
      id: '/_protected/sales/people/salesmen/$salesmanId/shops/$customerId'
      path: '/sales/people/salesmen/$salesmanId/shops/$customerId'
      fullPath: '/sales/people/salesmen/$salesmanId/shops/$customerId'
      preLoaderRoute: typeof ProtectedSalesPeopleSalesmenSalesmanIdShopsCustomerIdRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
  }
}

interface AuthLayoutRouteRouteChildren {
  AuthLayout2FaIndexRoute: typeof AuthLayout2FaIndexRoute
  AuthLayoutForgotPasswordIndexRoute: typeof AuthLayoutForgotPasswordIndexRoute
  AuthLayoutLoginIndexRoute: typeof AuthLayoutLoginIndexRoute
  AuthLayoutResetPasswordIndexRoute: typeof AuthLayoutResetPasswordIndexRoute
  AuthLayoutSignUpIndexRoute: typeof AuthLayoutSignUpIndexRoute
}

const AuthLayoutRouteRouteChildren: AuthLayoutRouteRouteChildren = {
  AuthLayout2FaIndexRoute: AuthLayout2FaIndexRoute,
  AuthLayoutForgotPasswordIndexRoute: AuthLayoutForgotPasswordIndexRoute,
  AuthLayoutLoginIndexRoute: AuthLayoutLoginIndexRoute,
  AuthLayoutResetPasswordIndexRoute: AuthLayoutResetPasswordIndexRoute,
  AuthLayoutSignUpIndexRoute: AuthLayoutSignUpIndexRoute,
}

const AuthLayoutRouteRouteWithChildren = AuthLayoutRouteRoute._addFileChildren(
  AuthLayoutRouteRouteChildren,
)

interface ProtectedReportsRouteRouteChildren {
  ProtectedReportsIndexRoute: typeof ProtectedReportsIndexRoute
  ProtectedReportsCollectionsIndexRoute: typeof ProtectedReportsCollectionsIndexRoute
  ProtectedReportsExpensesIndexRoute: typeof ProtectedReportsExpensesIndexRoute
  ProtectedReportsOutstandingIndexRoute: typeof ProtectedReportsOutstandingIndexRoute
  ProtectedReportsProfitLossIndexRoute: typeof ProtectedReportsProfitLossIndexRoute
  ProtectedReportsPurchasesIndexRoute: typeof ProtectedReportsPurchasesIndexRoute
  ProtectedReportsSalariesIndexRoute: typeof ProtectedReportsSalariesIndexRoute
  ProtectedReportsSalesIndexRoute: typeof ProtectedReportsSalesIndexRoute
  ProtectedReportsProfitLossProductProductIdIndexRoute: typeof ProtectedReportsProfitLossProductProductIdIndexRoute
  ProtectedReportsProfitLossRecipeRecipeIdIndexRoute: typeof ProtectedReportsProfitLossRecipeRecipeIdIndexRoute
}

const ProtectedReportsRouteRouteChildren: ProtectedReportsRouteRouteChildren = {
  ProtectedReportsIndexRoute: ProtectedReportsIndexRoute,
  ProtectedReportsCollectionsIndexRoute: ProtectedReportsCollectionsIndexRoute,
  ProtectedReportsExpensesIndexRoute: ProtectedReportsExpensesIndexRoute,
  ProtectedReportsOutstandingIndexRoute: ProtectedReportsOutstandingIndexRoute,
  ProtectedReportsProfitLossIndexRoute: ProtectedReportsProfitLossIndexRoute,
  ProtectedReportsPurchasesIndexRoute: ProtectedReportsPurchasesIndexRoute,
  ProtectedReportsSalariesIndexRoute: ProtectedReportsSalariesIndexRoute,
  ProtectedReportsSalesIndexRoute: ProtectedReportsSalesIndexRoute,
  ProtectedReportsProfitLossProductProductIdIndexRoute:
    ProtectedReportsProfitLossProductProductIdIndexRoute,
  ProtectedReportsProfitLossRecipeRecipeIdIndexRoute:
    ProtectedReportsProfitLossRecipeRecipeIdIndexRoute,
}

const ProtectedReportsRouteRouteWithChildren =
  ProtectedReportsRouteRoute._addFileChildren(
    ProtectedReportsRouteRouteChildren,
  )

interface ProtectedManufacturingProductionsRunIdRouteRouteChildren {
  ProtectedManufacturingProductionsRunIdIndexRoute: typeof ProtectedManufacturingProductionsRunIdIndexRoute
  ProtectedManufacturingProductionsRunIdCartonsIndexRoute: typeof ProtectedManufacturingProductionsRunIdCartonsIndexRoute
}

const ProtectedManufacturingProductionsRunIdRouteRouteChildren: ProtectedManufacturingProductionsRunIdRouteRouteChildren =
  {
    ProtectedManufacturingProductionsRunIdIndexRoute:
      ProtectedManufacturingProductionsRunIdIndexRoute,
    ProtectedManufacturingProductionsRunIdCartonsIndexRoute:
      ProtectedManufacturingProductionsRunIdCartonsIndexRoute,
  }

const ProtectedManufacturingProductionsRunIdRouteRouteWithChildren =
  ProtectedManufacturingProductionsRunIdRouteRoute._addFileChildren(
    ProtectedManufacturingProductionsRunIdRouteRouteChildren,
  )

interface ProtectedRouteRouteChildren {
  ProtectedReportsRouteRoute: typeof ProtectedReportsRouteRouteWithChildren
  ProtectedFinancePaymentVerificationRoute: typeof ProtectedFinancePaymentVerificationRoute
  ProtectedOperatorRunIdRoute: typeof ProtectedOperatorRunIdRoute
  ProtectedSalesOfflineRoute: typeof ProtectedSalesOfflineRoute
  ProtectedSuppliersSupplierIdRoute: typeof ProtectedSuppliersSupplierIdRoute
  ProtectedDashboardIndexRoute: typeof ProtectedDashboardIndexRoute
  ProtectedHrIndexRoute: typeof ProtectedHrIndexRoute
  ProtectedOperatorIndexRoute: typeof ProtectedOperatorIndexRoute
  ProtectedOrderBookerIndexRoute: typeof ProtectedOrderBookerIndexRoute
  ProtectedSuppliersIndexRoute: typeof ProtectedSuppliersIndexRoute
  ProtectedUserManagementIndexRoute: typeof ProtectedUserManagementIndexRoute
  ProtectedManufacturingProductionsRunIdRouteRoute: typeof ProtectedManufacturingProductionsRunIdRouteRouteWithChildren
  ProtectedHrAttendanceEmployeeIdRoute: typeof ProtectedHrAttendanceEmployeeIdRoute
  ProtectedHrAttendanceOfflineRoute: typeof ProtectedHrAttendanceOfflineRoute
  ProtectedHrEmployeesEmployeeIdRoute: typeof ProtectedHrEmployeesEmployeeIdRoute
  ProtectedHrOrderBookerDetailsEmployeeIdRoute: typeof ProtectedHrOrderBookerDetailsEmployeeIdRoute
  ProtectedManufacturingRecipesRecipeIdRoute: typeof ProtectedManufacturingRecipesRecipeIdRoute
  ProtectedSuppliersSupplierIdDetailsRoute: typeof ProtectedSuppliersSupplierIdDetailsRoute
  ProtectedDashboardActivityTimelineIndexRoute: typeof ProtectedDashboardActivityTimelineIndexRoute
  ProtectedFinanceAccountsIndexRoute: typeof ProtectedFinanceAccountsIndexRoute
  ProtectedFinanceExpensesIndexRoute: typeof ProtectedFinanceExpensesIndexRoute
  ProtectedFinanceLedgerIndexRoute: typeof ProtectedFinanceLedgerIndexRoute
  ProtectedHrApprovalsIndexRoute: typeof ProtectedHrApprovalsIndexRoute
  ProtectedHrAttendanceIndexRoute: typeof ProtectedHrAttendanceIndexRoute
  ProtectedHrEmployeesIndexRoute: typeof ProtectedHrEmployeesIndexRoute
  ProtectedHrPayrollIndexRoute: typeof ProtectedHrPayrollIndexRoute
  ProtectedHrSettingsIndexRoute: typeof ProtectedHrSettingsIndexRoute
  ProtectedInventoryFactoryFloorIndexRoute: typeof ProtectedInventoryFactoryFloorIndexRoute
  ProtectedInventoryWarehousesIndexRoute: typeof ProtectedInventoryWarehousesIndexRoute
  ProtectedManufacturingProductionsIndexRoute: typeof ProtectedManufacturingProductionsIndexRoute
  ProtectedManufacturingRecipesIndexRoute: typeof ProtectedManufacturingRecipesIndexRoute
  ProtectedOrderBookerCommissionIndexRoute: typeof ProtectedOrderBookerCommissionIndexRoute
  ProtectedOrderBookerOrdersIndexRoute: typeof ProtectedOrderBookerOrdersIndexRoute
  ProtectedOrderBookerRecoveriesIndexRoute: typeof ProtectedOrderBookerRecoveriesIndexRoute
  ProtectedOrderBookerTripsIndexRoute: typeof ProtectedOrderBookerTripsIndexRoute
  ProtectedSalesConfigurationsIndexRoute: typeof ProtectedSalesConfigurationsIndexRoute
  ProtectedSalesCustomersIndexRoute: typeof ProtectedSalesCustomersIndexRoute
  ProtectedSalesNewInvoiceIndexRoute: typeof ProtectedSalesNewInvoiceIndexRoute
  ProtectedSalesOrdersIndexRoute: typeof ProtectedSalesOrdersIndexRoute
  ProtectedSalesOverviewIndexRoute: typeof ProtectedSalesOverviewIndexRoute
  ProtectedSalesPeopleIndexRoute: typeof ProtectedSalesPeopleIndexRoute
  ProtectedSalesReconciliationIndexRoute: typeof ProtectedSalesReconciliationIndexRoute
  ProtectedSalesRecoveryIndexRoute: typeof ProtectedSalesRecoveryIndexRoute
  ProtectedHrPayrollEmployeeEmployeeIdRoute: typeof ProtectedHrPayrollEmployeeEmployeeIdRoute
  ProtectedInventoryFactoryFloorCartonsRecipeIdRoute: typeof ProtectedInventoryFactoryFloorCartonsRecipeIdRoute
  ProtectedFinanceExpensesSettingsIndexRoute: typeof ProtectedFinanceExpensesSettingsIndexRoute
  ProtectedHrPayrollEmployeeIndexRoute: typeof ProtectedHrPayrollEmployeeIndexRoute
  ProtectedManufacturingProductsProductIdIndexRoute: typeof ProtectedManufacturingProductsProductIdIndexRoute
  ProtectedSalesCustomersCustomerIdIndexRoute: typeof ProtectedSalesCustomersCustomerIdIndexRoute
  ProtectedSalesInvoicesInvoiceIdIndexRoute: typeof ProtectedSalesInvoicesInvoiceIdIndexRoute
  ProtectedSalesPeopleDistributorsCustomerIdLedgerRoute: typeof ProtectedSalesPeopleDistributorsCustomerIdLedgerRoute
  ProtectedSalesPeopleSalesmenSalesmanIdLedgerRoute: typeof ProtectedSalesPeopleSalesmenSalesmanIdLedgerRoute
  ProtectedSalesPeopleShopkeepersCustomerIdLedgerRoute: typeof ProtectedSalesPeopleShopkeepersCustomerIdLedgerRoute
  ProtectedInventoryItemItemTypeItemIdIndexRoute: typeof ProtectedInventoryItemItemTypeItemIdIndexRoute
  ProtectedSalesPeopleDistributorsCustomerIdIndexRoute: typeof ProtectedSalesPeopleDistributorsCustomerIdIndexRoute
  ProtectedSalesPeopleOrderBookersOrderBookerIdIndexRoute: typeof ProtectedSalesPeopleOrderBookersOrderBookerIdIndexRoute
  ProtectedSalesPeopleSalesmenSalesmanIdIndexRoute: typeof ProtectedSalesPeopleSalesmenSalesmanIdIndexRoute
  ProtectedSalesPeopleShopkeepersCustomerIdIndexRoute: typeof ProtectedSalesPeopleShopkeepersCustomerIdIndexRoute
  ProtectedSalesPeopleSalesmenSalesmanIdShopsCustomerIdRoute: typeof ProtectedSalesPeopleSalesmenSalesmanIdShopsCustomerIdRoute
}

const ProtectedRouteRouteChildren: ProtectedRouteRouteChildren = {
  ProtectedReportsRouteRoute: ProtectedReportsRouteRouteWithChildren,
  ProtectedFinancePaymentVerificationRoute:
    ProtectedFinancePaymentVerificationRoute,
  ProtectedOperatorRunIdRoute: ProtectedOperatorRunIdRoute,
  ProtectedSalesOfflineRoute: ProtectedSalesOfflineRoute,
  ProtectedSuppliersSupplierIdRoute: ProtectedSuppliersSupplierIdRoute,
  ProtectedDashboardIndexRoute: ProtectedDashboardIndexRoute,
  ProtectedHrIndexRoute: ProtectedHrIndexRoute,
  ProtectedOperatorIndexRoute: ProtectedOperatorIndexRoute,
  ProtectedOrderBookerIndexRoute: ProtectedOrderBookerIndexRoute,
  ProtectedSuppliersIndexRoute: ProtectedSuppliersIndexRoute,
  ProtectedUserManagementIndexRoute: ProtectedUserManagementIndexRoute,
  ProtectedManufacturingProductionsRunIdRouteRoute:
    ProtectedManufacturingProductionsRunIdRouteRouteWithChildren,
  ProtectedHrAttendanceEmployeeIdRoute: ProtectedHrAttendanceEmployeeIdRoute,
  ProtectedHrAttendanceOfflineRoute: ProtectedHrAttendanceOfflineRoute,
  ProtectedHrEmployeesEmployeeIdRoute: ProtectedHrEmployeesEmployeeIdRoute,
  ProtectedHrOrderBookerDetailsEmployeeIdRoute:
    ProtectedHrOrderBookerDetailsEmployeeIdRoute,
  ProtectedManufacturingRecipesRecipeIdRoute:
    ProtectedManufacturingRecipesRecipeIdRoute,
  ProtectedSuppliersSupplierIdDetailsRoute:
    ProtectedSuppliersSupplierIdDetailsRoute,
  ProtectedDashboardActivityTimelineIndexRoute:
    ProtectedDashboardActivityTimelineIndexRoute,
  ProtectedFinanceAccountsIndexRoute: ProtectedFinanceAccountsIndexRoute,
  ProtectedFinanceExpensesIndexRoute: ProtectedFinanceExpensesIndexRoute,
  ProtectedFinanceLedgerIndexRoute: ProtectedFinanceLedgerIndexRoute,
  ProtectedHrApprovalsIndexRoute: ProtectedHrApprovalsIndexRoute,
  ProtectedHrAttendanceIndexRoute: ProtectedHrAttendanceIndexRoute,
  ProtectedHrEmployeesIndexRoute: ProtectedHrEmployeesIndexRoute,
  ProtectedHrPayrollIndexRoute: ProtectedHrPayrollIndexRoute,
  ProtectedHrSettingsIndexRoute: ProtectedHrSettingsIndexRoute,
  ProtectedInventoryFactoryFloorIndexRoute:
    ProtectedInventoryFactoryFloorIndexRoute,
  ProtectedInventoryWarehousesIndexRoute:
    ProtectedInventoryWarehousesIndexRoute,
  ProtectedManufacturingProductionsIndexRoute:
    ProtectedManufacturingProductionsIndexRoute,
  ProtectedManufacturingRecipesIndexRoute:
    ProtectedManufacturingRecipesIndexRoute,
  ProtectedOrderBookerCommissionIndexRoute:
    ProtectedOrderBookerCommissionIndexRoute,
  ProtectedOrderBookerOrdersIndexRoute: ProtectedOrderBookerOrdersIndexRoute,
  ProtectedOrderBookerRecoveriesIndexRoute:
    ProtectedOrderBookerRecoveriesIndexRoute,
  ProtectedOrderBookerTripsIndexRoute: ProtectedOrderBookerTripsIndexRoute,
  ProtectedSalesConfigurationsIndexRoute:
    ProtectedSalesConfigurationsIndexRoute,
  ProtectedSalesCustomersIndexRoute: ProtectedSalesCustomersIndexRoute,
  ProtectedSalesNewInvoiceIndexRoute: ProtectedSalesNewInvoiceIndexRoute,
  ProtectedSalesOrdersIndexRoute: ProtectedSalesOrdersIndexRoute,
  ProtectedSalesOverviewIndexRoute: ProtectedSalesOverviewIndexRoute,
  ProtectedSalesPeopleIndexRoute: ProtectedSalesPeopleIndexRoute,
  ProtectedSalesReconciliationIndexRoute:
    ProtectedSalesReconciliationIndexRoute,
  ProtectedSalesRecoveryIndexRoute: ProtectedSalesRecoveryIndexRoute,
  ProtectedHrPayrollEmployeeEmployeeIdRoute:
    ProtectedHrPayrollEmployeeEmployeeIdRoute,
  ProtectedInventoryFactoryFloorCartonsRecipeIdRoute:
    ProtectedInventoryFactoryFloorCartonsRecipeIdRoute,
  ProtectedFinanceExpensesSettingsIndexRoute:
    ProtectedFinanceExpensesSettingsIndexRoute,
  ProtectedHrPayrollEmployeeIndexRoute: ProtectedHrPayrollEmployeeIndexRoute,
  ProtectedManufacturingProductsProductIdIndexRoute:
    ProtectedManufacturingProductsProductIdIndexRoute,
  ProtectedSalesCustomersCustomerIdIndexRoute:
    ProtectedSalesCustomersCustomerIdIndexRoute,
  ProtectedSalesInvoicesInvoiceIdIndexRoute:
    ProtectedSalesInvoicesInvoiceIdIndexRoute,
  ProtectedSalesPeopleDistributorsCustomerIdLedgerRoute:
    ProtectedSalesPeopleDistributorsCustomerIdLedgerRoute,
  ProtectedSalesPeopleSalesmenSalesmanIdLedgerRoute:
    ProtectedSalesPeopleSalesmenSalesmanIdLedgerRoute,
  ProtectedSalesPeopleShopkeepersCustomerIdLedgerRoute:
    ProtectedSalesPeopleShopkeepersCustomerIdLedgerRoute,
  ProtectedInventoryItemItemTypeItemIdIndexRoute:
    ProtectedInventoryItemItemTypeItemIdIndexRoute,
  ProtectedSalesPeopleDistributorsCustomerIdIndexRoute:
    ProtectedSalesPeopleDistributorsCustomerIdIndexRoute,
  ProtectedSalesPeopleOrderBookersOrderBookerIdIndexRoute:
    ProtectedSalesPeopleOrderBookersOrderBookerIdIndexRoute,
  ProtectedSalesPeopleSalesmenSalesmanIdIndexRoute:
    ProtectedSalesPeopleSalesmenSalesmanIdIndexRoute,
  ProtectedSalesPeopleShopkeepersCustomerIdIndexRoute:
    ProtectedSalesPeopleShopkeepersCustomerIdIndexRoute,
  ProtectedSalesPeopleSalesmenSalesmanIdShopsCustomerIdRoute:
    ProtectedSalesPeopleSalesmenSalesmanIdShopsCustomerIdRoute,
}

const ProtectedRouteRouteWithChildren = ProtectedRouteRoute._addFileChildren(
  ProtectedRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthLayoutRouteRoute: AuthLayoutRouteRouteWithChildren,
  ProtectedRouteRoute: ProtectedRouteRouteWithChildren,
  ApiHealthRoute: ApiHealthRoute,
  AttendanceScanRoute: AttendanceScanRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiInternalBootstrapAdminRoute: ApiInternalBootstrapAdminRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
